### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by jannikbuscha** [ismail9k/vue3-carousel#10]
Hello,
I can't use the framework in a vue 3 typescript project.
What can I do about it?

TS7016: Could not find a declaration file for module 'vue3-carousel'. 'C:/Users/Jannik/PhpstormProjects/backify-landing/node_modules/vue3-carousel/dist/carousel.js' implicitly has an 'any' type.
  Try `npm install @types/vue3-carousel` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-carousel';`

**Comment by nahojj** [comment]
@ismail9k This doesn't work.. I get the same issue. Any fix?

**Comment by yesworld** [comment]
I faced the same problem :(

**Comment by zetashift** [comment]
Running into the same problem!

**Comment by ibnujakaria** [comment]
any update on this issue?

**Comment by LanShih** [comment]
I added two options into "compilerOptions" in tsconfig.json,then it works.
"allowJs": true,
"noImplicitAny": false,

**Comment by minhlong** [comment]
> I added two options into "compilerOptions" in tsconfig.json,then it works. "allowJs": true, "noImplicitAny": false,

@LanShih ,

It works, you saved me =))

Tks,

**Comment by ismail9k** [comment]
fixed in `v0.1.42`

**Comment by suryachansrasoi** [comment]
I am facing the same problem
