### ISSUE TITLE
First image doesnt get the --active class unless i click something in carousel

### ISSUE THREAD

**Issue by vasilistotskas** [ismail9k/vue3-carousel#100]
Hello , i noticed that the first image doesn't get active unless i click on arrow , navigation or somewhere inside carousel section .
images bellow : first image is when i refresh the page , second is when i click on carousel .

![1st](https://user-images.githubusercontent.com/60323306/134801223-6e623cf8-7cd1-409a-a76b-e1b88062403c.png)
![2nd](https://user-images.githubusercontent.com/60323306/134801225-84e1f12c-a28a-4b9b-a880-f60acc784cad.png)

.

**Comment by YetAnotherLuke2** [comment]
Any updates on this? same issue here

**Comment by afrazahmmad** [comment]
Facing same issue

**Comment by afrazahmmad** [comment]
I had to do this manullay. But its working fine.
     
     let elem_  = document.querySelector('.carousel__pagination').firstElementChild.firstElementChild;
        if (elem_ && !elem_.classList.contains('carousel__pagination-button--active')){
            elem_.classList.add('carousel__pagination-button--active');
        }

**Comment by ValeryZheleznov** [comment]
I'm facing the same issue for several weeks. Trying to find a walkaround before it will be resolved.
I presume the problem is in "undefined" default value for the "modelValue" prop. See line 80 in the Carousel component:
https://github.com/ismail9k/vue3-carousel/blob/master/src/components/Carousel.ts

Is there any ideas how to change it in mounted() hook?

**Comment by ValeryZheleznov** [comment]
Got it!

mounted() {
            let buttonsNext = document.getElementsByClassName('carousel__next');
            if (buttonsNext.length > 0) {
                buttonsNext.item(0).click();
            }
        },

Works for me.
Hope this will help
