### ISSUE TITLE
Slide pagination

### ISSUE THREAD

**Issue by kurokh** [ismail9k/vue3-carousel#110]
Hi! Thanks for plugin!
But I would suggest to add slide pagination. Because if I have for example 8 items and set it to `:items-to-show = "4"` in this case I don't need 8 pagination links it's enough to have 2 and slide by 4 elements.

Thanks!

**Comment by neoighodaro** [comment]
Ping... same issue

**Comment by Sorrow81** [comment]
Hi, I am trying to add a pagination like @ak215. Do you have a workaround?

**Comment by ismail9k** [comment]
@Sorrow81 You can create your own component similar to [this](https://github.com/ismail9k/vue3-carousel/blob/master/src/components/Pagination.ts) and maybe create a pr with this addition ;)
