### ISSUE TITLE
not correctly working when itemsToShow > 3 

### ISSUE THREAD

**Issue by Charsune** [ismail9k/vue3-carousel#111]
### Subject of the issue
thanks for sharing such a great package

I use 3 carousel in same page。Carousel not correctly working when itemsToShow > 3, I don't know that something wrong I have did 

like this:

![截圖 2021-11-01 上午10 08 16](https://user-images.githubusercontent.com/33538421/139614314-427f32de-a331-423d-a6a4-ceb1c6601a9f.png)
code:

<img width="506" alt="截圖 2021-11-01 上午10 39 17" src="https://user-images.githubusercontent.com/33538421/139614337-5ba27a7e-a841-4099-ab6c-6ae41b64adb6.png">

<img width="385" alt="截圖 2021-11-01 上午10 45 15" src="https://user-images.githubusercontent.com/33538421/139614529-7fac1e1a-db3b-4a2c-8be5-246ea1600fcd.png">

package
    "vue": "^3.0.0",
    "vue3-carousel": "^0.1.29"
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5"

**Comment by Charsune** [comment]
more details
![截圖 2021-11-01 上午11 11 49](https://user-images.githubusercontent.com/33538421/139616680-c78ff265-1d63-4732-8754-26831b2d41bb.png)

**Comment by ismail9k** [comment]
Related to #108

**Comment by Charsune** [comment]
thank you
