### ISSUE TITLE
When there are 4 or less slides with wrapAround, transition is broken

### ISSUE THREAD

**Issue by LucianHij** [ismail9k/vue3-carousel#120]
https://codesandbox.io/s/ncpb8

The issue is seen in the codesandbox. When swiping the transition is broken.

**Comment by omni-frontend-dev** [comment]
Transition from does break when there are 4 or less.

**Comment by lackoSK** [comment]
I can confirm the issue is present, four or fewer slides - the transition is not behaving as supposed.

**Comment by sonjinh9862** [comment]
if there a four slides, transition got breaking. it must to slide right to left but reversed.

**Comment by LucianHij** [comment]
@ismail9k are you still maintaining this package? Or we should search for another solution outthere?

**Comment by fyapy** [comment]
This issue has been fixed in `v0.1.32`

**Comment by GeorgyLevin** [comment]
> This issue has been fixed in `v0.1.32`

Its not. With 2 slides and warpAround=true it allways slide to the right no matter what arrow you press.
