### ISSUE TITLE
Buttons inside carousel first touch on mobile does not work

### ISSUE THREAD

**Issue by LucianHij** [ismail9k/vue3-carousel#121]
For a carousel that has buttons inside, on `mobile`, with `mouseDrag = false`, on first touch the on click event for button is not called. After first touch, everything works perfect. 

See this example. The issue is on second carousel with buttons, but you have to change your browser into mobile view. You will notice that on first click, the console log does not appear.
https://codesandbox.io/s/ncpb8

**Comment by ghighi3f** [comment]
I'm having the same problem
On vue3-carousel - "version": "0.1.29"

**Comment by ghighi3f** [comment]
Found the solution here #46

**Comment by LucianHij** [comment]
I will try, but this is only a workaround. We need a proper fix for this.

**Comment by mdmullins** [comment]
possible solution is to use touchmove as a disabler for the touchend event: 

```
<Slide
  v-for="item in items"
  :key="item"
  @touchend="handleClick"
  @touchmove="handleTouchMove"
>

const canClick = ref(true);
const handleTouchMove = () => {
  canClick.value = false;
};
const handleProductClick = (product: MenuItem) => {
  if (canClick.value) {
     // do what you want with the click
  } else {
    canClick.value = true;
  }
}
```

**Comment by lucasantunes-ciandt** [comment]
Having this issue as well, also on 0.1.29
