### ISSUE TITLE
Quasar framework dont import Components

### ISSUE THREAD

**Issue by athamour1** [ismail9k/vue3-carousel#122]
**Describe the bug**
In Quasar framework, I can't import components such as Slide

**To Reproduce**
- I followed the documentation example and I used composition API 
- I imported the components with ```import { Carousel, Slide, Navigation } from "vue3-carousel";```
- i defined the components with 
```vue 	
components: {
  Carousel,
  Navigation,
  Slide
}
```

**Expected behavior**
To load the components

**Screenshots**
in this screenshot, I was trying to use the components with lowercase the same results I have with the first letter uppercase.
![image](https://user-images.githubusercontent.com/39333862/142167018-745520ab-6502-47f3-b575-aafac0d6bfc9.png)

**Desktop**
 - OS: Pop-OS 21.04
 - Browser: chrome
 - Version: Version 95.0.4638.69 (Official Build)  (64-bit)

**Comment by athamour1** [comment]
also i have tried to implement them with [this](https://v3.vuejs.org/guide/migration/custom-elements-interop.html#overview) method

**Comment by ismail9k** [comment]
This issue is fixed in the latest version, closing it
