### ISSUE TITLE
Autoplay wraparound enabled shows all slides when changing slides

### ISSUE THREAD

**Issue by Ethan-Hill** [ismail9k/vue3-carousel#123]
Currently when you have `wrapAround` and `autoplay` enabled it shows all the slides with one slide change.

Is there a way to have it so it only changes 1 slide and not show all slides when changing?

**Comment by kos195** [comment]
I believe what you're looking for is the `itemsToScroll` prop but its default value is already `1`. Have you maybe set it by mistake in your settings to a different value?

**Comment by mattbra1155** [comment]
I had an issue where I didn't set the itemsToScroll and just used the defaults. It showed around 1.3 instead od 1. After setting it to 1 in settings it works

**Comment by aochoa8a** [comment]
A little late, but had the same problem. My carousel had 4 elements, added the itemsToScroll, and set its value to 3. Made the autoplay run normally but from right to left. Hope it helps!

**Comment by fyapy** [comment]
> A little late, but had the same problem. My carousel had 4 elements, added the itemsToScroll, and set its value to 3. Made the autoplay run normally but from right to left. Hope it helps!

Could you provide some reproduction repository or codesandbox?

**Comment by aochoa8a** [comment]
> > A little late, but had the same problem. My carousel had 4 elements, added the itemsToScroll, and set its value to 3. Made the autoplay run normally but from right to left. Hope it helps!
> 
> Could you provide some reproduction repository or codesandbox?

Yesterday I noticed my solution worked when it comes to the autoplay but it messed up the manual change of slides with the arrows as the items to scroll were set to 3. Just realized that the author fixed the wrap-around issue 5 days ago, installed the new version, and works like a charm.
