### ISSUE TITLE
Bug: wrap-around work incorrect when items-to-show equal to 1

### ISSUE THREAD

**Issue by fyapy** [ismail9k/vue3-carousel#129]
**Describe the bug**
wrap-around work incorrect when items-to-show equal to 1.

**To Reproduce**
1. Create component 
```vue
<template>
  <Carousel :items-to-show="1" :wrap-around="true">
    <Slide v-for="slide in 10" :key="slide">
      <div class="carousel__item">{{ slide }}</div>
    </Slide>
    
    <template #addons>
      <Navigation />
    </template>
  </Carousel>
</template>
```
2. Paginate to next slide to see wrong behavior. When you move from the first to the second slide, the carousel rotates completely.

**Expected behavior**
Transition from first slide, to second slide. Without full rotation of the carousel.

**Pull request**
https://github.com/ismail9k/vue3-carousel/pull/128

**Comment by fyapy** [comment]
Ohh, issue duplicate https://github.com/ismail9k/vue3-carousel/issues/120

**Comment by fyapy** [comment]
Solved!

**Comment by fyapy** [comment]
Solved!

**Comment by ismail9k** [comment]
Thanks for your contribution :)
