### ISSUE TITLE
is it compatible with vue2?

### ISSUE THREAD

**Issue by bruno2kd** [ismail9k/vue3-carousel#13]

**Comment by ismail9k** [comment]
Currently, this library is targeting Vue 3, maybe in the future when we can adapt for Vue 2 too.

**Comment by ismail9k** [comment]
I am planning to support Vue 2 also through [vue-demi](https://github.com/vueuse/vue-demi).

**Comment by djcaesar9114** [comment]
I think it may be better to focus on current features development as more and more developers are migrating to vue3.
