### ISSUE TITLE
When using router.push to go to a different route (where there is a carousel component) everything about the carousel is broken

### ISSUE THREAD

**Issue by LucianHij** [ismail9k/vue3-carousel#131]
**Describe the bug**
Carousel is totally broken when using vue-router to navigate to a route that has vue-carousel used.

**To Reproduce**
1. Create 2 "pages" 
2. Navigate using vue-router from the first page to the second one
3. The second page should have the vue-carousel component implemented
4. Observe that the carousel is not working at all when changing routes

**Expected behavior**
The carousel to work

**Comment by lacorde** [comment]
This issue is similar to #134. Would also like to know !

**Comment by LucianHij** [comment]
Still does not work

**Comment by LucianHij** [comment]
So, it works only on first mount. But if you are navigating by switching the pages again, the second time the carousel is dead. Also, the carousel is dead if you use `v-show` on it.

**Comment by deStrO** [comment]
I'm having the same behavior, when I navigate between pages, slider doesn't update properly (in nuxt3)

**Comment by lacorde** [comment]
I have the same behavior as @deStrO (also nuxt3)

**Comment by busken2** [comment]
Can also confirm this bug / behavior (Nuxt3)

**Comment by denisasJersovas** [comment]
the issue is still there, any news about the fix maybe ?
