### ISSUE TITLE
Fraction non-wrapping jumps to start when last slide is reached

### ISSUE THREAD

**Issue by mdmullins** [ismail9k/vue3-carousel#133]
**Describe the bug**

When adding a fractional itemsToShow, a bug appears when scrolling on non-wrapping content. Upon reaching the last slide, the carousel jumps to the start and is unable to drag to scroll any more.

**To Reproduce**
1. Go to https://codesandbox.io/s/cool-chebyshev-c85il?file=/src/App.vue
2. Drag carousel to the left until you reach the last slide
3. Carousel will jump to the start
4. Unable to drag to scroll any more

**Expected behavior**
Carousel should scroll to the final slide then stop at the last.

**Screenshots**

https://user-images.githubusercontent.com/7125495/144874910-ded7e47b-2dda-493c-9c8e-0735c97ce23d.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 96

**Comment by lacorde** [comment]
Hi @ismail9k , thank you for the great plugin !
I can confirm I have the same issue, with itemsToShow set to a fraction.
Carousel jumps at start instead of reaching last slide when clicking clicking the navigation (so it's not a drag-specific behavior).

**Comment by lacorde** [comment]
Fix confirmed ! Thanks for the quick update.
