### ISSUE TITLE
Additional function to call to navigate the carousel manually.

### ISSUE THREAD

**Issue by lackoSK** [ismail9k/vue3-carousel#136]
**Is your feature request related to a problem? Please describe.**
Additional function to call to navigate the carousel manually.

**Describe the solution you'd like**
 Instead of having to use the standard navigation feature, it would be great if we could manually call the next() or prev() methods to navigate the carausel.

**Describe alternatives you've considered**
I thought of a solution where we could use reference to the carousel and call it from there.

`
<carousel ref="foobar">
...
</carousel>`

**Additional context**
`<button @click="$refs.foobar.next()>next</button>`

**Comment by ismail9k** [comment]
Carousel methods exposed on `v0.1.35`
