### ISSUE TITLE
V-model to access slide number

### ISSUE THREAD

**Issue by djcaesar9114** [ismail9k/vue3-carousel#14]
**Is your feature request related to a problem? Please describe.**
The carousel is great but I can't access the current slide number, neither in get or set.
   
**Describe the solution you'd like**
I'd like, for example, to access the current slide number like this:
`<carousel v-model="activeSlide">`

And in my parent component I want to be able to GET this "activeSlide" and SET it if I want.

**Describe alternatives you've considered**
An alternative, for the moment, is to put a child component in the slide, and when I click on this component it updates a parent prop.

**Additional context**
None

**Comment by ismail9k** [comment]
You can now access the `currentSlide` value through the slots attributes check: https://ismail9k.github.io/vue3-carousel/getting-started.html#slots-attributes.
