### ISSUE TITLE
Go to specific slide

### ISSUE THREAD

**Issue by nahojj** [ismail9k/vue3-carousel#141]
Is it possible to get to a specific slide to active/first on click? So if I have a button that always goes to a specific index of the slides when clicking?

**Comment by ismail9k** [comment]
Yes you can do so using carousel component reference
```vue
<template>
  <Carousel ref="myCarousel">
  ...
  </Carousel>
<template>

<script>
{
  ...
  handleButtonClick() {
    this.$refs.myCarousel.slideTo(1);
  }
 }
</script>
```
