### ISSUE TITLE
how to change active dot color and border-radius

### ISSUE THREAD

**Issue by myomyintaung1411** [ismail9k/vue3-carousel#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ismail9k** [comment]
You can achieve this easily by overwriting the pagination styles. Check the current pagination [styles](https://github.com/ismail9k/vue3-carousel/blob/master/src/styles/pagination.css)

You can also overwrite the CSS variables related to each property you want, before importing the carousel styles file, for example `--vc-pgn-background-color`, `--vc-pgn-active-color`, etc

**Comment by Burwin** [comment]
I'm probably an idiot, but I've wasted too much time on this. Do you happen to have an example of overriding these colors in a Vue3 component?
