### ISSUE TITLE
Slides doesn't load if reactive array empty

### ISSUE THREAD

**Issue by djcaesar9114** [ismail9k/vue3-carousel#15]
**Describe the bug**
When using a reactive array to generate the carousel, the slides don't load if the array is empty at the creation of the component. You have to set the array with a value inside.

**To Reproduce**
In the composition API, create a reactive variable like this:

```
  setup() {
    const new = reactive({
      title: '',
      attachments: [],
    });
```

Fetch the news with something like this:

```
    onMounted(async () => {
      fetchNews(route.params.id);
    });
```

Although everything is loaded everywhere, the carousel doesn't update, it remains empty.
If you want the carousel to have its slides, you have to set the variable like this:

```
  setup() {
    const new = reactive({
      title: '',
      attachments: [''],
    });
```

**Expected behavior**
The carousel should load its slides even if the array is empty.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by ismail9k** [comment]
Fixed in `v0.1.13`
