### ISSUE TITLE
Sliding with modelValue not work

### ISSUE THREAD

**Issue by rasstislav** [ismail9k/vue3-carousel#150]
Hello, I have the following issue / question:

When modelValue is set, sliding to the previous / next slide (click in navigation / pagination or drag) not work.
It returns to the original slide. Is it a desired condition or bug? Please watch the attached video / [code pen](https://codepen.io/rasstislav/pen/XWzpMaw).

Thank you for your response.

https://user-images.githubusercontent.com/9253113/152847730-565127ad-4feb-4c31-8c5e-1b2cfe50696f.mov

**Comment by kostya110393** [comment]
Hi! I had this problem but could solve it. You need put :key from index element - 
<Slide v-for="(item, index) of banners" :key="index">
I hope that it help you.

**Comment by rasstislav** [comment]
> Hi! I had this problem but could solve it. You need put :key from index element - I hope that it help you.

Hi @kostya110393! I don't know what you mean. Could you send a code sample?

**Comment by kostya110393** [comment]
> > Привет! У меня была эта проблема, но я смог ее решить. Вам нужно поставить :key из индексного элемента - я надеюсь, что это поможет вам.
> 
> Привет @kostya110393 ! Я не знаю, что вы имеете в виду. Не могли бы вы отправить образец кода?

`<Slide v-for="(item, index) of banners" :key="index"></Slide>`

**Comment by rasstislav** [comment]
The solution doesn't work for me. You can try making changes in this example: https://codepen.io/rasstislav/pen/XWzpMaw.

**Comment by kostya110393** [comment]
> @kostya110393 The solution doesn't work for me. You can try making changes in this example: https://codepen.io/rasstislav/pen/XWzpMaw.

https://codepen.io/Kostya93/pen/ExbLxep

**Comment by rasstislav** [comment]
It looks good. Thanks @kostya110393!
