### ISSUE TITLE
How can I prevent scrolling while sliding on mobile?

### ISSUE THREAD

**Issue by schosdas** [ismail9k/vue3-carousel#153]
Hello
I'm a beginner at vue.js.

I want to touch the carousel on the mobile so that the vertical scroll does not work when sliding. (Only horizontal sliding while touching)
Does this plug-in include features for this?
Thank you.

**Comment by danbohea** [comment]
Also looking for this functionality after recent client feedback.

**Comment by magFixCorp** [comment]
Just use following css
.carousel .carousel__slide--visible,
.carousel__track,
.carousel__viewport {
  -ms-touch-action: pan-x;
  touch-action: pan-x;
}

**Comment by ismail9k** [comment]
@magFixCorp Nice workaround!

**Comment by axelkennedal** [comment]
@magFixCorp this is only a partial solution. Applying pan-x makes it so that the user cannot scroll vertically _at all_ on the carousel. It should still be possible to swipe up and down on the carousel to scroll the entire page up and down.

**Comment by riderx** [comment]
hey @ismail9k i saw you merged a fix, but i still have the issue, should i apply the css solution here to have the fix ?
