### ISSUE TITLE
How to call slideTo() from an event?

### ISSUE THREAD

**Issue by mmvahora** [ismail9k/vue3-carousel#157]
Hi, new to Vue and web development. 

How would I go about using the slideTo() method/API call if I wanted to add the ability to click on a slide and then have that slide become the active one?

Using the basic examples, I have set up click events which pass the slide number to my function. How can I have this function call the slideTo() method and get the desired outcome? 

Is this currently possible? Or is it something I would have to program into the package itself? Thanks!

**Comment by m8brgarc** [comment]
I can't get this to work either.

**Comment by ismail9k** [comment]
Please check this example for more info: https://ismail9k.github.io/vue3-carousel/examples.html#custom-navigation
