### ISSUE TITLE
auto play infinite mode

### ISSUE THREAD

**Issue by sunny-repo88** [ismail9k/vue3-carousel#158]
Example:
5 images in carousel.

Currently the implementation:
Auto play will stop at 5th image.

Suggestion:
Auto play will not stop at 5th image and will keep loop from first image to 5th image
1->2->3->4->5->1->2->3->4->5 (infinite mode)

**Comment by rashidpathiyil** [comment]
[Autoplay Example (Infinite) ](https://github.com/ismail9k/vue3-carousel/blob/master/docs/examples/ExampleAutoplay.vue)](https://ismail9k.github.io/vue3-carousel/examples.html#autoplay-example)

**Comment by ismail9k** [comment]
Thanks @rashidpathiyil for answering this. I will close this issues then
