### ISSUE TITLE
Including carousel in a flex component breaks the navigation

### ISSUE THREAD

**Issue by djcaesar9114** [ismail9k/vue3-carousel#16]
**Describe the bug**
When the carousel is inside a component with a flex display, you can't navigate through slides properly.

**To Reproduce**
Put the carousel in a div:
```
        <div id="diaporama">
          <carousel :items-to-show="1">
              ...
```

Set the CSS of the div:
```
#diaporama {
  display: flex;
  align-items: center;
}
```

**Expected behavior**
I expect the carousel to be vertically aligned inside the div and the navigation to display the slides completely.

**Screenshots**
https://ibb.co/vPMHtbv
https://ibb.co/PFShFZh
https://ibb.co/zrKDFQw

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by ismail9k** [comment]
This is a working [example](https://codesandbox.io/s/vue3-carousel-example-02-tsgpu) of a carousel wrapped in a flex-box container
