### ISSUE TITLE
show more than 1 in same time

### ISSUE THREAD

**Issue by albericobenhur** [ismail9k/vue3-carousel#170]
hi, I'm not able to show more than one item at the same time, how could I do that?

**Comment by ismail9k** [comment]
Hi, please check [Docs](https://ismail9k.github.io/vue3-carousel/getting-started.html#available-props) for a list of the available props.

And here some [examples](https://ismail9k.github.io/vue3-carousel/examples.html) on how to use them

**Comment by albericobenhur** [comment]
thank you
