### ISSUE TITLE
Links and button based slides get triggered when dragging on desktop

### ISSUE THREAD

**Issue by OliverJEvans** [ismail9k/vue3-carousel#175]
**Describe the bug**
- I have slides which are made up of anchors with hrefs or buttons with @click events
- On desktop when dragging the carousel on mouseup the anchor is clicked.
- This issue doesn't exist on mobile

**To Reproduce**
https://codesandbox.io/s/thirsty-mestorf-sjhtqt?file=/src/App.vue
- Above link has a carousel with multiple slides containing buttons
- Open console of codesandbox
- Click on slide and drag
- On release of mouse, console log triggered

**Expected behavior**

- As mobile, when draging carousel button and anchor actions not triggered.
- When not dragging clicking button triggers event

**Screenshots**
![Kapture 2022-04-13 at 14 16 08](https://user-images.githubusercontent.com/4497135/163188617-01c8dd16-27b3-4839-b38b-dff356764318.gif)

**Desktop (please complete the following information):**
 - OS: Mac OSX 12.3.1
 - Browser: Chrome
 - Version: 100.0.4896.88

**Comment by woken-token** [comment]
Same behaviour on Windows 10 in Chrome.

**Comment by Naresh-Khatri** [comment]
Same thing when an `a` tag is wrapped inside `<Slide>`

**Comment by ismail9k** [comment]
@Naresh-Khatri We can not prevent links/buttons from being clicked at all, however after daring it will prevent the click event from being handled.

This is the same example with the latest carousel version `0.1.40`
https://user-images.githubusercontent.com/11035467/166887052-a4bfed80-91b1-4646-a3d8-c5277468db5d.mov

**Comment by Naresh-Khatri** [comment]
It was a fault on my end I got it working now but there's still a problem. 
When I try to drag a slide having an `<a>` tag with `href` attr it starts dragging the link and not the actual slide as shown.
I fixed that by adding `draggable='false'` to `<a>` but now it opens up the link when dragging is done.


https://user-images.githubusercontent.com/32219857/166948339-c4cb29ad-9920-4f35-a2d3-48465fe6daee.mp4

**Comment by ismail9k** [comment]
@Naresh-Khatri This should be fixed in the latest version

**Comment by franco-onevillas** [comment]
Hey there @ismail9k @Naresh-Khatri , how did you solve this? I have something like this but its opening the link every time I drag on desktop

```
<Slide v-for="post in posts" :key="post.id" class="px-4">
  <a :href="post.permalink" target="_blank" draggable="false">
     <img :src="post.media_url" class="w-full h-[385px] object-cover" />
  </a>
</Slide>
```

**Comment by Naresh-Khatri** [comment]
@franco-onevillas It was fixed right after when I posted it, BTW I have been using another carousel ([Splide](https://splidejs.com/)) these days and that doesn't have this problem by default.

**Comment by franco-onevillas** [comment]
@Naresh-Khatri thank you so much, looks promising! cheers
