### ISSUE TITLE
[BUG] "Wrap Around" property messes up the order of items

### ISSUE THREAD

**Issue by chescobarf** [ismail9k/vue3-carousel#177]
**Describe the bug**
I'm witnessing this bug, that when declaring the property wrap-around=true, when looking at the elements it renders, they change the order in which they were declared.

**To Reproduce**
To reproduce we do the following:
-  First, we create the component and pass this prop to true.

```
<template>
  <Carousel :items-to-show="3" :wrap-around="true" :itemsToScroll="1">
    <slide v-for="slide in 4" :key="slide">
      <div class="slide bg-secondary-900 shadow-md">{{ slide }}</div>
    </slide>
  </Carousel>
</template>
```
- Then we go to observe the site
- Here we can observe the following, the items appear in the following order:  3 - 4 - 1

![image](https://user-images.githubusercontent.com/44533046/164779334-186e2761-2a7e-44c6-96c4-26b57d969c98.png)

- However when we pass the slide once, the latter is in the following order: 1 - 2 - 3

![image](https://user-images.githubusercontent.com/44533046/164780494-f66222f4-8259-4246-8e8e-e3f37d0e174a.png)

- When the true order that should happen is: 4 - 1 - 2

**Expected behavior**
The expected behavior would be that this first of all would start with the item 1 - 2 - 3
and with each change only move 1 or the amount indicated in the property

**Additional context**
As additional information, this was tested on Chrome, using Vue 3 and Nuxt 3.
For the rest, this behavior can also be observed on the demo page of the library:

https://ismail9k.github.io/vue3-carousel/examples.html#wrap-around

If you reload the site you will be able to observe the same thing, it appears with an order and then when you slide, it changes completely.

**Comment by ismail9k** [comment]
Hi @chescobarf, Acutely this is the normal behavior for the carousel component. 
By enabling wrapping around the carousel reorder the slides so that there will be enough slides when you move to back and forward. Moreover, on this, there's a property called `snapAlign` which accepts the following values `start`, `end`, `center`, `center-odd`, and `center-even`. You can try one those values to find the best alignment that would fit your use case.
