### ISSUE TITLE
Carousel viewport overflowing from parent div if image is too big

### ISSUE THREAD

**Issue by djcaesar9114** [ismail9k/vue3-carousel#18]
**Describe the bug**
The carousel is inside a div (flexed).
I have several big images in the carousel, and I put max-height and max-width so that the images fit.

**To Reproduce**
Insert the carousel like this:

```
        <div id="diaporama">
          <carousel :items-to-show="1" wrapAround>
            <slide
              v-for="(item, i) in files"
              :key="`carousel-${i}`">
              <div class="diapo">
                {{ item.description }}<br />
                <img
                  :src="`${apiUrl}/files/${item.id}`"/>
              </div>
            </slide>

            <template #addons>
              <navigation />
              <pagination />
            </template>
          </carousel>

        </div>
```

The relevant CSS is this one:

```
#diaporama {
  flex: 0 1 90%;
  padding: 0 50px;
  max-height: 100%;
  overflow-y: hidden;
}

#diaporama img {
  max-width: 100%;
  max-height: 100%;
}
```

**Expected behavior**
I expect the images to fit perfectly in the carousel, not overflowing horizontally or vertically.

**Screenshots**
https://ibb.co/28XXWNL

** Override workaround
I managed to update the CSS property like this, just after having loaded what would fill the images:

```
          nextTick(() => {
            const els = document.querySelectorAll('.diapo img');
            for (let x = 0; x < els.length; x += 1) {
              els[x].style['max-height'] = `${document.getElementById('diaporama').clientHeight - 100}px`;
            }
          });
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by ismail9k** [comment]
This carousel is very minimal; that's why it doesn't handle every custom use case. since most use cases could be handled easily using CSS.
