### ISSUE TITLE
Src property inside img element not working as intended

### ISSUE THREAD

**Issue by Arturexe** [ismail9k/vue3-carousel#180]
I'm trying to get following code to run but the image elements get rendered as broken:
```

<template>
  <div id="gallery" class="gallery">
    <carousel :items-to-show="1.5" class="slider">
      <slide v-for="slide in ar" :key="slide">
        <img :src="'@/images/' + slide" alt="">
      </slide>
      <template #addons>
        <navigation/>
        <pagination/>
      </template>
    </carousel>

<!--    test image (works)-->
    <img src="@/images/main.jpg" alt="" style="width: 20%; height: 10rem;">

  </div>
</template>


<script setup>
import 'vue3-carousel/dist/carousel.css'
import {Carousel, Slide, Pagination, Navigation} from 'vue3-carousel'

const ar = ['dummy.jpg', 'logo.png', 'main.jpg']

</script>
```

Is this a bug or am I doing it wrong?

**Comment by ismail9k** [comment]
This is not the carousel issue, you can validate this by updating the test image to the following

```html
<img :src="'@/images/' + 'main.jpg'" alt="" style="width: 20%; height: 10rem;">
```

For more on this problem, you can check this [Vue.js dynamic images not working](https://stackoverflow.com/questions/40491506/vue-js-dynamic-images-not-working)

**Comment by nehalshah50** [comment]
This issue exists in Vue3+Vite. In my case few displayed slides upfront shows images but the slides which are not yet shown doesn't load images and its intermittent. Sometime it shows and sometime it doesn't. When it does not show then you swipe back & forth the slides and it starts showing
