### ISSUE TITLE
Not animate slides if v-model is not first slide

### ISSUE THREAD

**Issue by alisaliso** [ismail9k/vue3-carousel#183]
**Is your feature request related to a problem? Please describe.**
Hi! I'm using your library and I have a minor issue with it. When I'm clicking on the image preview and open slider, instead of showing the image I clicked the slider scrolls to this image and the scroll is very noticeable.

**Describe the solution you'd like**
You can add a prop like noAnimateScrollTo that will show image without scroll animation

**Describe alternatives you've considered**
I've tried to remove scroll animation via css but it wasn't successful.

**Comment by AlotOfBlahaj** [comment]
same question

**Comment by ismail9k** [comment]
As a workaround, you can set the `transition` value to zero
