### ISSUE TITLE
TypeScript types don't get published to NPM

### ISSUE THREAD

**Issue by fabis94** [ismail9k/vue3-carousel#184]
**Describe the bug**
This package does generate TS typings (.d.ts) files and even references them in the package.json "types" field, but the "dist/index.d.ts" field doesn't actually exist in the published npm package tarball. Maybe it's removed by something (I don't see anything offending in .npmignore), but whatever the case may be, TypeScript types are broken for this package.

**To Reproduce**
Just `npm i` the latest version and check the package contents in `node_modules`

**Expected behavior**
`dist/index.d.ts` should be available in the package tarball

**Comment by fabis94** [comment]
I built this repo locally and it looks like the actual location of the types is `dist/src/index.d.ts`

**Comment by 07JP27** [comment]
I'm facing same issue.
Are there any workarounds until fixed this bug?

**Comment by fabis94** [comment]
> I'm facing same issue. Are there any workarounds until fixed this bug?

Augment the types yourself - create a .d.ts file with a `declare module 'vue3-carousel'` block and fill it with the types from the actual types file you can build when checking out this project locally.

... or use swiper.js

**Comment by 07JP27** [comment]
@fabis94 Thank you! I will try.

**Comment by ismail9k** [comment]
fixed in `v0.1.43`
