### ISSUE TITLE
Carousel returned to initial position when scrolling

### ISSUE THREAD

**Issue by ismael-albert** [ismail9k/vue3-carousel#189]
when I define the modelValue prop, when I scrool the carousel it returns to the initial position, is there a possibility to disable this return to the initial position?

**Comment by texperia** [comment]
Are you still facing this problem? I have the exact same problem

**Comment by ismael-albert** [comment]
Yes

**Comment by shababps** [comment]
I also experience this problem , any help will be great

**Comment by Amaurgit** [comment]
Same problem here :(

**Comment by ismail9k** [comment]
This issue should be fixed in the newest version, I will close it for now. Please feel free to reopen it if the issue happens again.
