### ISSUE TITLE
Add looping feature.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [ismail9k/vue3-carousel#19]
**Is your feature request related to a problem? Please describe.**
Please add looping feature.

**Describe the solution you'd like**
For instance it may be called:  loop. And can get true or false values as a boolean.

**Describe alternatives you've considered**
Slick, Swiper
**Additional context**
No any other content.

**Comment by ismail9k** [comment]
If you mean slides warping around, we already have a boolean for it `wrapAround`. For more info please check [available props](https://github.com/ismail9k/vue3-carousel#available-props)

**Comment by OtabekSadiridinov** [comment]
Oh, thank you i didn't know. Thanks.
