### ISSUE TITLE
Carousel now sticks to cursor after 0.1.4

### ISSUE THREAD

**Issue by xrayian** [ismail9k/vue3-carousel#190]
**Describe the bug**
When I click and hold any image to drag, it gets fixed to the cursor. 
this was fine in 0.1.38

**To Reproduce**
all carousels are affected like this
```vue
<Carousel :autoplay="7000" :wrapAround='true' :breakpoints="breakpoints" snapAlign="center">
            <Slide v-for="slide in showcasePhotos" :key="slide">
                <div class="carousel__item"><img :src='getImageUrl(slide)'></div>
            </Slide>
</Carousel>
```

**Expected behavior**
It shouldn't stick

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 102

**Comment by gerardfollano** [comment]
Any update on this. Experiencing this as well.

**Comment by xrayian** [comment]
@gerardfollano I couldn't find any usable solution in the current version, I just reverted to 0.1.38.

**Comment by alisaliso** [comment]
Same problem
