### ISSUE TITLE
Maximum recursive updates exceeded in the component <Carousel>. 

### ISSUE THREAD

**Issue by PhinehasSersah** [ismail9k/vue3-carousel#191]
Getting this warn message trying to use the Carousel component  -- runtime-core.esm-bundler.js:38 [Vue warn]: Maximum recursive updates exceeded in component <Carousel>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by PhinehasSersah** [comment]
The data that v-for loops over is async data, could it be the case? maybe when the data is in a pending state

**Comment by TheYakuzo** [comment]
You need to set a "v-if" on Carousel component on the data you loop on

**Comment by ismail9k** [comment]
Closing this issue since it's fixed in the latest version.
