### ISSUE TITLE
Wrong width calculated

### ISSUE THREAD

**Issue by mobius77** [ismail9k/vue3-carousel#192]
In this construction of flex somethind wrong with caurusel's width. On any device.
It's ok when we have 4 slides, but if we have 7 or more something goes wrong.

import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap"

`<div class="d-flex">
            <div class="d-flex">
                <div class="align-self-center">
                    <button class="btn btn-primary">=</button>
                </div>
            </div>
            <div class="flex-fill">
                <CategoryCarousel />
            </div>
        </div>`

settings: {
      itemsToShow: 1,
      itemsToScroll: 1,
      snapAlign: 'center',
    },

**Screenshots**
![зображення](https://user-images.githubusercontent.com/10038730/173634245-de23e485-5538-4bc5-bdf3-d433c29191fd.png)

**Comment by rahi-MTL** [comment]
same problem

**Comment by jmarshalld33** [comment]
I'm also hitting this issue

**Comment by ismail9k** [comment]
This issue should be fixed in the newest version, I am closing it. Please feel free to reopen this issue if something goes wrong.
