### ISSUE TITLE
Support custom slots next and previous

### ISSUE THREAD

**Issue by lequangdongg** [ismail9k/vue3-carousel#199]

**Comment by karolissaint** [comment]
If it helps, for navigation arrows you already could use 
``` 
<template #addons>
      <Navigation>
         <template #next> some next icon </template>
         <template #prev> some prev icon </template>
      </Navigation>
</template>
``` 
inside you carousel component

**Comment by minhlong** [comment]
> If it helps, for navigation arrows you already could use
> 
> ```
> <template #addons>
>       <Navigation>
>          <template #next> some next icon </template>
>          <template #prev> some prev icon </template>
>       </Navigation>
> </template>
> ```
> 
> inside your carousel component

It works for me.
Thanks you,

**Comment by lequangdongg** [comment]
> If it helps, for navigation arrows you already could use
> 
> ```
> <template #addons>
>       <Navigation>
>          <template #next> some next icon </template>
>          <template #prev> some prev icon </template>
>       </Navigation>
> </template>
> ```
> 
> inside your carousel component

Thanks, it works for me
