### ISSUE TITLE
how to pause/resume autoplay on clicking buttons

### ISSUE THREAD

**Issue by youjin-10** [ismail9k/vue3-carousel#204]
I wanted to add buttons to pause and resume autoplay of vue3-carousel. 
So I tried to change the value of 'autoplay' dynamically and when I set the value to 0 (number zero) it started looping through slides very fast instead of stopping autoplay. 
Is there any proper way to pause and resume autoplay? 

Thanks in advance!

**Comment by animeshsarkar-bct** [comment]
Did they support this feature?

**Comment by lecappa** [comment]
Hello !!

Did they support this feature ?
