### ISSUE TITLE
MouseDrag not working correctly

### ISSUE THREAD

**Issue by dwagner320** [ismail9k/vue3-carousel#206]
When I click on the slides the mousedrag is not working correctly. Seems like you need to click a couple of times and then it works halfway. Seems like you need to hold the mouse click and then release it. Also I am not sure if the images are in a transition if the click has any effect at all. Is that problem in another version also? I am using version 0.1.40.

**Comment by CKGrafico** [comment]
Similar experience here, I can only drag to the first slide, after this I cannot drag anymore.

**Comment by CKGrafico** [comment]
Nothing about this? I'm still not able to guess how to fix it :(
