### ISSUE TITLE
V-model and slideTo not selecting right key item

### ISSUE THREAD

**Issue by nmeynard** [ismail9k/vue3-carousel#207]
**Describe the bug**
Using v-model doesn't take the focus on the right item (using key in slides and passing the key value to v-model).
SlideTo slide to another item when using the value of the key of an item.

**To Reproduce**
Use v-model directive or slideTo according to what's written in the docs and examples.

**Expected behavior**
V-model should give focus to the item which has this value in "key" directive.
SlideTo should give focus to the item which has this value in "key" directive.

**Desktop (please complete the following information):**
 - OS: All platforms
 - Browser All browsers

**Comment by nmeynard** [comment]
+ the plugin randomly throw "too much recursion" error, works sometimes after multiple refresh, but absolutely random.

**Comment by ismail9k** [comment]
This issue is fixed on the latest version
