### ISSUE TITLE
Vue Carousel 3 With gallery thumbnails sync

### ISSUE THREAD

**Issue by amoralesdesign** [ismail9k/vue3-carousel#208]
Hi, is there any way to make a typical product gallery? With large photos and thumbnails for browsing.

I don't know if this option exists in Vue 3 Carousel, I haven't found a code with this example.
Like splide carousel[ Thumbnails example](https://splidejs.com/).
![Captura de pantalla 2022-08-05 a las 11 11 22](https://user-images.githubusercontent.com/4416148/183044717-7a215747-6e57-4a81-a8d0-e022782660a6.jpg)

**Comment by ismail9k** [comment]
Check this example for more info: https://ismail9k.github.io/vue3-carousel/examples.html#gallery
