### ISSUE TITLE
swiping(right to left) is not working when there are two slides

### ISSUE THREAD

**Issue by youjin-10** [ismail9k/vue3-carousel#216]
When there are only two slide items and I try to swipe them right to left, the value of translateX becomes zero(0px) and it makes swiping works weird
I think it happens because 'next slide' and 'prev slide' is same when there are two slides... Please correct this bug.

**Comment by ismail9k** [comment]
Please provide me with the full carousel example and configs, and what version you are using.

**Comment by youjin-10** [comment]
version: 0.1.46
I haven't changed any configs since I installed this library..

code:
<img width="461" alt="스크린샷 2022-08-17 오후 3 32 29" src="https://user-images.githubusercontent.com/105618795/185050552-0c798450-892e-4d96-9515-aa82479123a2.png">
