### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Ischafak** [ismail9k/vue3-carousel#217]
First of all thank you for this awesome component. there is some bugs i want to mention.

1-

```
<template>
  <Carousel :items-to-show="3" :wrap-around="true">
    <Slide v-for="slide in 4" :key="slide">
      <div class="carousel__item bg-green w-full">{{ slide }}</div>
    </Slide>

    <template #addons>
      <Navigation />
    </template>
  </Carousel>
</template>
```

when i press right button it renders not smooth. Next item renders instantly after 1 second there is no transition animation. but if i give 5 item to v-for it works smooth.

2- for :items-to-show="1" and v-for="slide in 2" i press right arrow but animation goes left side so it feels weird.

**Comment by ismail9k** [comment]
Fixed in `v0.2.0`
