### ISSUE TITLE
Sliding does notwork on iOS

### ISSUE THREAD

**Issue by Tettsch** [ismail9k/vue3-carousel#22]
**Describe the bug**
Sliding in the basic vue carousel example does not work on an iPhone Xs.

**To Reproduce**
1. Go to 'https://ismail9k.github.io/vue3-carousel/examples.html.'
2. Try to slide to the right
3. Does not work

**Smartphone (please complete the following information):**
 - Device:[e.g. iPhone Xs
 - OS: e.g. 14.4
 - Browser stock safari

We also tried to embed the carousel into our website, which also did not work on various iPhone models.

**Comment by antssanjeewa** [comment]
The same question came to me. 
Please try to resolve this issue.

**Comment by Arias-xss** [comment]
I have the same issue, please solve this 

Smartphone (please complete the following information):

Device: iPhone 12
OS: 14.6
Browser: Chrome

**Comment by e81u4g** [comment]
I find adding this style can work

.carousel__slide--visible > .carousel__item {
  transform: rotateY(0);
}

but I don't know why ...

ref: https://ismail9k.github.io/vue3-carousel/examples.html#autoplay-example

**Comment by TotomInc** [comment]
@e81u4g I can confirm, the fix seems to work on iOS 15.1 (Chrome and Safari).

**Comment by ginuim** [comment]
> I find adding this style can work
> 
> .carousel__slide--visible { transform: rotateY(0); }
> 
> but I don't know why ...
> 
> ref: https://ismail9k.github.io/vue3-carousel/examples.html#active-classes

It works, Thank you!
