### ISSUE TITLE
drag will change click event listeners

### ISSUE THREAD

**Issue by amir94rp** [ismail9k/vue3-carousel#222]
I have one or two anchor tag in my slides and I have defined click event for them

    <template>
	    <a :href="href" @click.prevent="manual_visit">
		    <slot></slot> 
	    </a>
    </template>  
    <script> 
    export default {
	    props:{  
	        href:{  
	            required:true
            }  
         },  
	    methods:{  
	        manual_visit:function (e){ 
	          console.log('click')
	        }  
	    } 
    }  
    </script>
befor I start to drag if I click this anchor it will prevent the default behavior and will log the 'click' text but if I start and end the drag from this element , my click event listener will be removed and default behavior will be done.

[![ezgif-1-f0d1e685a6.gif](https://i.postimg.cc/9QqfHDng/ezgif-1-f0d1e685a6.gif)](https://postimg.cc/QFhDpdsc)

**Comment by rinoj** [comment]
I need help with this aswell.

**Comment by ismail9k** [comment]
@rinoj Could you share a working [code sandbox example](https://codesandbox.io/) which demonstrates your full issue, it will help me to came up with a fix for your issue.
