### ISSUE TITLE
Text Input, Textarea not working on slides

### ISSUE THREAD

**Issue by Georg7** [ismail9k/vue3-carousel#226]
**Describe the bug**
My slides include various form elements (radio buttons, checkboxes, text input, textarea). When clicking on the text input or textarea, the elements don't focus, hence making it not possible for user to type text. Radio buttons and checkboxes work as expected.

**To Reproduce**
```
       <Carousel>
          <Slide v-for="slide in 10" :key="slide">
            <div>{{ slide }}</div>
            <input type="text" />
           <textarea></textarea>
          </Slide>
       </Carousel>
```
**Expected behavior**
Element focuses when use clicks on it.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 104.0.5112.101

**Comment by narkane** [comment]
for now your best solution is going to be passing in the carousel props to disable dragging via elements. looks like:
    <Carousel :mouse-drag="false" :touch-drag="false">
      <Slide v-for="slide in 2" :key="slide">
        <div>{{ slide }}</div>
        <input type="text" />
        <input type="radio" />
        <textarea></textarea>
      </Slide>
      <template #addons>
        <Navigation />
        <Pagination />
      </template>
    </Carousel>
    
    for ex
    
    im currently working on building in an exclusion for textfields
