### ISSUE TITLE
TS2307: Cannot find module '@/types' or its corresponding type declarations

### ISSUE THREAD

**Issue by bjornharrtell** [ismail9k/vue3-carousel#227]
Getting this error:

node_modules/vue3-carousel/dist/carousel.d.ts:3:29 - error TS2307: Cannot find module '@/types' or its corresponding type declarations.
 
... when generating type declarations using vite-plugin-dts. Unsure if it's a bug here or in vite-plugin-dts, but the latter seem to work fine with other things.

**Comment by ismail9k** [comment]
Fixed in `v0.1.47`
