### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded at mapNumberToRange

### ISSUE THREAD

**Issue by ADCJustinH** [ismail9k/vue3-carousel#234]
**Describe the bug**
When creating a carousel with 1 item and autoplay enabled this error occurs.

**To Reproduce**
Use version 0.2.0  **(This does not error in 0.1.48)** 

Create carousel with 1 slide that scrolls:
```
 <carousel :items-to-show="3.5" :autoplay="3500">
...
</carousel>
```

wait 3.5 secs and see error in console.

**Expected behavior**
no error

**Comment by ismail9k** [comment]
fixed in `v0.2.1`
