### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rdytwm** [ismail9k/vue3-carousel#24]
reactivity.esm-bundler.js?a1e9:722 Uncaught RangeError: Maximum call stack size exceeded
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252
slideTo @ carousel.es.js?0b81:252

**Comment by ismail9k** [comment]
Hi @rdytwm could you provide me with a minimal working example, which generates the issue?
