### ISSUE TITLE
Is it possible to set a delay between transitions?

### ISSUE THREAD

**Issue by neilcarpenter007** [ismail9k/vue3-carousel#242]
The default time between each transition is too quick imo.
Is there anoption to add a delay between transitions when auto play is true that isn't documented anywhere?

It would be ideal for the carousel component to accept a prop that determines how long to wait between each transition when autoplay is set to true.

I think I could probably disable autoplay, and write my own loop with a setTimeout that triggers the next() method on the component on each iteration. But doing this feels like overkill, and I think it makes sense for a "delay" to be a config option.

**Comment by neilcarpenter007** [comment]
Please accept my apologies for me being a moron.

I've just read the docs properly and realised the autoplay prop defines the autplay time in ms.

I assumed that autoplay was a boolean for whether the carousel should be autoplay or not.

**Comment by ismail9k** [comment]
No issues at all, glad it worked for you :)
