### ISSUE TITLE
Auto resize based on container size

### ISSUE THREAD

**Issue by mysticseagull** [ismail9k/vue3-carousel#243]
**Is your feature request related to a problem? Please describe.**
The use case I am proposing as I found it an issue in my case is that I am unable to resize the carousel with the div as it isn't changing its mobile response state based on the parent container rather it does it from the page as a whole.

**Describe the solution you'd like**
I propose that a configuration key is added such as "scaleToParent: (True/False)" to enable it to be useful in things that are not screen size dependant. 

**Describe alternatives you've considered**
Alternatives I have tried are a old out of date vue 2 version of a similar carousel, and or creating plans to make my own. though I feel this use case would be beneficial to the package and the community that uses it.

**Comment by navaneeth-automatad** [comment]
Hi, is there update on this ?

**Comment by tarwin** [comment]
I created a pull request - https://github.com/ismail9k/vue3-carousel/pull/388 which should add this for you.
