### ISSUE TITLE
incorrect maxSlide version ^0.2.5

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [ismail9k/vue3-carousel#259]
maxSlide is set to 0 when component first mounted which breaks carousel navigation. I attempted resetting carousel after mounted using various carousel methods, but none of them working. maxSlide value gets set correctly only after force update of component. Version 0.2.4 works fine.

**Comment by ismail9k** [comment]
Could you help me debug this by providing a minimal working code that generates the issue?

**Comment by ismail9k** [comment]
Closed due to inactivity
