### ISSUE TITLE
Carousel is not emitting events

### ISSUE THREAD

**Issue by axelkennedal** [ismail9k/vue3-carousel#262]
**Describe the bug**
According to [the documentation](https://ismail9k.github.io/vue3-carousel/api/events.html) there are two events `slide-start` and `slide-end` that should be emit by the Carousel component when sliding starts and ends.

These events are never emitted.

**To Reproduce**

Create a Carousel like so:

```
<template>
  ...
  <Carousel @slide-start="handleSlideStart">...
</template>

<script setup>
  const handleSlideStart = () => {
    // this is never called...
    console.log("slide start")
  }
  ...
</script>
```

**Expected behavior**
When using the Carousel on a mobile device/emulator and swiping left/right the function `handleSlideStart` in the example above should be called.

**Screenshots**
N/a.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 108

**Comment by igormaozao** [comment]
Same error here, no event is been emit.

I'm not on mobile or emulator, just a regular desktop.

Windows 10
Chrome 108

**Comment by sosog** [comment]
@axelkennedal try @slideStart it can be just compiling runtime issue, not the package. Please copy your package.json if it doesn't help you.

**Comment by axelkennedal** [comment]
Unfortunately I cannot provide my code, but yes it does indeed seem to work from @ismail9k `s example. So I guess we can close this.
