### ISSUE TITLE
Option to scroll after user has swiped

### ISSUE THREAD

**Issue by axelkennedal** [ismail9k/vue3-carousel#266]
**Is your feature request related to a problem? Please describe.**
When a user on mobile tries to scroll up and down on a page which uses this carousel the contents of the carousel also begins to scroll - as it follows the swipe of the user _while_ the user is swiping.

**Describe the solution you'd like**
Add an option (boolean) to the Carousel component, e.g. `slideAfterSwipe`.

When false, don't change behaviour.

When true: The carousel should not scroll its slides while the user is swiping. Instead it should only perform scrolls _after_ the user has made a complete swipe. This way it is easy for the Carousel to know if the user actually meant to scroll the carousel, or just scroll up and down on the page. An example of this is how [the Bootstrap carousel](https://getbootstrap.com/docs/5.2/components/carousel/#with-controls) works.

**Describe alternatives you've considered**
I have proposed a small fix for the scrolling in mobile issue [here](https://github.com/ismail9k/vue3-carousel/issues/153). But it is not perfect.

Also, in addition to this feature fixing the scrolling issue, it is simply a new way to customize the behaviour of the carousel, which is nice.

**Additional context**
N/a.

**Comment by ismail9k** [comment]
The carousel component now uses [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to controls scrolling when carousel drag
