### ISSUE TITLE
Missing callback's

### ISSUE THREAD

**Issue by seetpalsingh** [ismail9k/vue3-carousel#27]
I am missing the callback to destory if only one slide, or show no arrows on single slide

**Describe the solution you'd like**
I wanted to automate this to show no navigation/pagination/drag/slide if only single slide

**Describe alternatives you've considered**
create callbacks or remove those arrows and drag slide function

**Additional context**
Thanks you for simple carousel :D

**Comment by seetpalsingh** [comment]
We also need option to disable drag slide options.

otherwise you can provide options attribute to deliver calculated options.

**Comment by ismail9k** [comment]
You can achieve this easily, by continually render the carousel, as following:
```vue
<Carousel v-if="items.length > 1">
  ...
  <template #addons>
    <Navigation />
    <Pagination />
  </template>
</Carousel>

<img v-else-if="items.length === 1" :src="items[0].src" alt="item[0].name" />
<img v-else :src="/img/blank.jpg" alt="Blank Image" />
```

If you want to disable the navigation addons only you can do this using addons [slot attributes](https://ismail9k.github.io/vue3-carousel/getting-started.html#slots-attributes)

```vue
<Carousel>
   ...
  <template #addons="{ slidesCount }">
    <Navigation v-if="slidesCount > 1" />
  </template>
</Carousel>
```
