### ISSUE TITLE
A way to style of card indexes other than active, next, prev and other

### ISSUE THREAD

**Issue by Reddevildragg** [ismail9k/vue3-carousel#270]
**Is your feature request related to a problem? Please describe.**
ultimately Looking for a way to determine what slides are partially off the screen / how far they are away from the focused image

in the example below would look to have the center 5 items at 100% opacity and the corner 2 at 60%
![image](https://user-images.githubusercontent.com/19800074/210782177-7eed1588-e6b0-401b-869d-1974adaf8a3b.png)

From what i can see there is no way to pull this information out of the current structure and best case can have the center, next, prev at 100% but everything else at 60%

Though looking in the code/vue dev tools it looks liek every slide has an index (which could then use that - slides to show would let me know what index from center a slide is and use css to style accordingly), but could not find a way to access this variable or the slide data as looks like it is not exposed.

**Describe the solution you'd like**
A way to apply style to slides outside of the active, prev, next, other system

**Comment by ismail9k** [comment]
You can find an example in the documentation for active classes [here](https://vue3-carousel.ismail9k.com/examples.html#active-classes).
