### ISSUE TITLE
Isn't there any Changelog?

### ISSUE THREAD

**Issue by DMOAbove** [ismail9k/vue3-carousel#272]
So, I am working on a project that makes use of this carousel and we're using version 0.1.36, and my idea was to update to last version. But I don't see any kind of changelog, so I dunno which bugs were solved neither if there is any breaking change.

Would be great to include a Changelog on the project. And if you can resume me if there is anything I should now before update, I would appreciate.

**Comment by ismail9k** [comment]
Changelog file has been added
