### ISSUE TITLE
Slider width isn't calculated properly

### ISSUE THREAD

**Issue by IamMilev** [ismail9k/vue3-carousel#274]
Carousel slide isn't calculating the right slide width. I am passing itemsToShow to be one and receive 4 items.

const carouselSettings = {
  itemsToShow: 1,
  itemsToScroll: 1,
  autoplay: 5000,
  wrapAround: true,
  snapAlign: "center",
};

![Screenshot 2023-01-25 163156](https://user-images.githubusercontent.com/50167243/214590509-89c43c31-d53f-43e3-8198-b59ef8990f78.png)

**Comment by IamMilev** [comment]
I think I found what is the issue, on mount it gets the width of the carousel section which is 254px and after populating the slides it doesn't recalculate the proper slide width

**Comment by josepuma** [comment]
I'm having the same issue using nuxt3 :/

**Comment by tinkerbaj** [comment]
Same issue

**Comment by tinkerbaj** [comment]
I fix it by adding absolute to element inside slider

**Comment by dbelouslv** [comment]
I have the same issue, but my slider located in tabs. I have just added `<Carousel v-if="currentTabIndex === 2"` and it is works for me.

**Comment by ismail9k** [comment]
@RamaHerbin Instead of triggering window resize you could directly reset the carousel values by using this [method](https://ismail9k.github.io/vue3-carousel/api/methods.html#restartcarousel)

**Comment by RamaHerbin** [comment]
This works perfectly. Thank you

**Comment by ismail9k** [comment]
Fixed in `v0.2.24`
