### ISSUE TITLE
Vue3-carousel gives me an impact on site performance

### ISSUE THREAD

**Issue by t-bee** [ismail9k/vue3-carousel#276]
### Vue3-carousel gives me an impact on site performance

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.)

Chrome console:
![chrome-console](https://user-images.githubusercontent.com/11809223/216755427-93d878e1-2f93-47ae-aa34-59e50c160518.PNG)

Lighthouse performance issue:
![lighthouse](https://user-images.githubusercontent.com/11809223/216755431-a74e5a92-bc5e-4805-9dfe-bcbc557c2a8d.PNG)

As far as I search, the solution is to add "{passive: true}" to each addEventListener and removeEventListener, I tried but with no luck. 
Is there anyone currently fixing this part?

**Update:** The "Avoid an excessive DOM size" diagnostics warning was my bad (solved). "non-passive event listener....." issues still exist.

**Comment by J-Sek** [comment]
I've added [#7764](https://github.com/vuejs/core/issues/7764) for Vue 3.
