### ISSUE TITLE
NUXT 3 support?

### ISSUE THREAD

**Issue by ronbonqqq** [ismail9k/vue3-carousel#282]
Can I use this component in NUXT 3? If yes, how? If no, when is NUXT 3 support planned?

**Comment by arashsheyda** [comment]
yes it works in nuxt 3.
https://github.com/ismail9k/vue3-carousel#basic-using

**Comment by ismail9k** [comment]
Here is a working [example](https://stackblitz.com/edit/github-1vtnku?file=components/BasicCarousel.vue) with Nuxt@3.0.0

**Comment by gaetansenn** [comment]
Hello @ismail9k i have created a nuxt module for your library :) 

https://github.com/gaetansenn/vue3-carousel-nuxt
