### ISSUE TITLE
css error all messed up

### ISSUE THREAD

**Issue by migueljr** [ismail9k/vue3-carousel#284]
**Describe the bug**
I try to install the lib but the css gets all messed up.

**To Reproduce**
just install according to the documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/12215747/225629557-cc08fc77-1bc3-402c-83be-4d78131dd0cb.png)
The image above is how it looks in the browser. I don't have any errors in the console

![image](https://user-images.githubusercontent.com/12215747/225629977-24cab4ca-ecd1-4317-a691-dd9aa178fe27.png)
the image above is how the code is.

am I doing something wrong?

**Comment by ismail9k** [comment]
I don't see any issue in your code, could you share some more details for example Vue and the plugin versions? Also it would be helpful if you could share a minimal working example that regenerates your issue.

**Comment by ismail9k** [comment]
Closed due to inactivity
