### ISSUE TITLE
Passive issue with 'touchstart' event still present in latest version (0.2.13) of npm package

### ISSUE THREAD

**Issue by ydh-thegachee** [ismail9k/vue3-carousel#286]
It appears that the latest version (0.2.13) of the vue3-carousel package on npm still has the passive issue with the 'touchstart' event, despite the fact that a related issue has already been resolved. (#276). 

Specifically, the code in the latest version of the package on npm still contains the problematic code.
([/vue3-carousel/dist/carousel.es.js, line 643](https://www.npmjs.com/package/vue3-carousel?activeTab=code))

I am not sure where to report this issue, so I am posting it here for now.

**Comment by ismail9k** [comment]
Thank you for raising this. Please update to version v0.2.14, and if you still facing the same problem feel free to reopen the issues again
