### ISSUE TITLE
vue3-carousel/carousel.css file not exist .

### ISSUE THREAD

**Issue by maytham553** [ismail9k/vue3-carousel#287]
This is my code ... 
![Screenshot 2023-03-24 at 6 00 36 PM](https://user-images.githubusercontent.com/51288320/227562248-58854a6c-eb29-446c-b2a1-32f9f951bcfd.png)

![Screenshot 2023-03-24 at 6 00 45 PM](https://user-images.githubusercontent.com/51288320/227562275-17376b00-fd50-4259-90d6-6b2f7c1d6fca.png)

And I get this error ... 
Compiled with problems:
ERROR in ./src/components/sliders/BigSliders.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/sliders/BigSliders.vue?vue&type=script&lang=js) 4:0-36
Module not found: Error: Can't resolve 'vue3-carousel/carousel.css' in '/Users/maythammahdi/Desktop/Singularity/Binaa mall/binaa-mall/src/components/sliders'

![Screenshot 2023-03-24 at 6 03 49 PM](https://user-images.githubusercontent.com/51288320/227562944-2ded5a75-1f66-47fa-9c0d-90186d149679.png)

**Comment by ChantalDelachevrotiere** [comment]
I also get this. is the `'vue3-carousel/carousel.css'`  intended for when you want to update the css? I was able to alter only some of the style but for instance I was not able to edit the arrows

**Comment by ismail9k** [comment]
Could you replace the URL to be `'vue3-carousel/carousel.css'`

**Comment by ismail9k** [comment]
Docs updated with the correct path
