### ISSUE TITLE
Vertical sliding

### ISSUE THREAD

**Issue by Trixpua** [ismail9k/vue3-carousel#289]
Is there some plan to support vertical sliding?

**Comment by ismail9k** [comment]
I am currently focusing on horizontal sliding, supporting vertical sliding could take me some time to support.

**Comment by Sirojiddin96** [comment]
is there any news on this feature? vertical feature will be added? @ismail9k

**Comment by l-besenyei** [comment]
I'm also interested in this feature, is there any progress  on this?

**Comment by triplecasquette** [comment]
Also interrested @ismail9k :)
