### ISSUE TITLE
Problems when sliding

### ISSUE THREAD

**Issue by weathon** [ismail9k/vue3-carousel#31]
(used with vue and ionic)

It always stays at page one whatever you do. But if I change the window size it will work again.

Code:
```vue
<template>
  <Carousel>
    <Slide v-for="slide in 10" :key="slide">
      <div style="width:50px;background-color:purple">{{ slide }}</div>
    </Slide>

    <template #addons>
      <Navigation />
      <Pagination />
    </template>
  </Carousel>
</template>

<script lang="ts">
import "vue3-carousel/dist/carousel.css";
import { Carousel, Slide, Pagination, Navigation } from "vue3-carousel";
export default {
  name: "Tab1",
  components: {
    Carousel,
    Slide,
    Pagination,
    Navigation,
  },
};
</script>
```

**Comment by weathon** [comment]
I think it is a problem of ionic, though

**Comment by weathon** [comment]
If I add the code after the page is loaded, it works. But if I add it before, it doesn't

**Comment by ismail9k** [comment]
What is the version of vue3-carousel, you are using?

**Comment by weathon** [comment]
The latest

**Comment by ismail9k** [comment]
In order to help me debugging this issue could you provide me with a minimal working example, on [CodeSandbox](https://codesandbox.io/) or [JSfiddle](https://jsfiddle.net/)

**Comment by weathon** [comment]
Sorry for the late response, I figured it out. It is ionic's issue. Thank you

**Comment by Pankechi** [comment]
> Sorry for the late response, I figured it out. It is ionic's issue. Thank you

Hey, i'm faced with exact the same problem, using Vue3 and compositiopn API. Please, can you tell me how did u fixed this problem?

**Comment by ahpoo** [comment]
@Pankechi 
This is my first post on a Github Issue, so apologies if it's hard to read.

A temporary solution is described below. Please try it.
`<Carousel ref="myCarousel"> ... </Carousel>`

`import { ref } from 'vue'`

```
setup() {
  const myCarousel = ref(null)

  onMounted(async () => {
    ... 
    get some images 
    ...
    (myCarousel.value as any).updateSlidesData();
  });

  return {
    myCarousel,
  }
}

```

**Comment by Pankechi** [comment]
@ahpoo 

Sttill not working for me.

Here's template:
`<Carousel 
      :settings="settings"
      ref="myCarousel" 
      :items-to-scroll= "1">

      <Slide 
        v-for="product in props.product_list" 
        :key="product.id">

        <ProductCard 
          :key="product.id" 
          :product_card="product"/>

      </Slide>

      <template #addons>

        <Navigation class="nav" />

        <Pagination />

      </template>

      </Carousel>`

And script part: 
`const props = defineProps({
  product_list: Array
})

const myCarousel = ref(null)

onMounted(() => myCarousel.value.updateCarousel())

const settings = {
  breakpoints: {
    390: {
        itemsToShow: 1,
    },
    600: {
      itemsToShow: 2,
    },
    1024: {
        itemsToShow: 3,
    },
    1366: {
        itemsToShow: 4,
    },
    1920: {
        itemsToShow: 5,
    },
  }
}`

But thank you a lot for the answer.

**Comment by Pankechi** [comment]
@ahpoo 
Still not working for me. Here's my code.
But anyway, thanks a lot for the answer. 

```
const myCarousel = ref(null)

onMounted(() => myCarousel.value.updateCarousel())
```
