### ISSUE TITLE
How can I use carousel combined if data is from props (array of objects) and if I want to use slot

### ISSUE THREAD

**Issue by tiborAntalInterway** [ismail9k/vue3-carousel#310]
Im using carousel component (u-carousel) actually like this:

![image](https://github.com/ismail9k/vue3-carousel/assets/92582122/1542bef0-ac37-4429-9a36-c852c00f3ab2)

and I want to have option, when I want to push slides not from prop dataSlides but from parent component (using slots), like this:

![image](https://github.com/ismail9k/vue3-carousel/assets/92582122/29347a4b-30fd-4171-a9d1-662594bb8b40)

is possible to do it? thanks

**Comment by ismail9k** [comment]
Using `v-html` is not recommended, here's an example to achieve what you would like to:

```vue
// UCarousel
<template>
  <Carousel v-show="items.length" :wrap-around="true" snap-align="center">
    <template #slides>
       <slot />
    </template>

    <template #addons>
      <Navigation />
      <Pagination />
    </template>
  </Carousel>
</template>
```

```vue
// SlideWrapper
<template>
  <div class="carousel__item">
     <div class="carousel__content">
         <slot />
     </div>
  </div>
</template>
```

And use it like the following:

```vue
<template>
  <UCarousel >
      <SlideWrapper>Slide 1</SlideWrapper>
      <SlideWrapper>Slide 2</SlideWrapper>
      <SlideWrapper>Slide 3</SlideWrapper>
  </UCarousel>
</template>
```


If your data are strings, with no need for passing HTML elements you can simply go with


```vue
// UCarousel
<template>
  <Carousel v-show="items.length" :wrap-around="true" snap-align="center">
    <Slide v-for="(item, indx) in items" :key="indx">
      <div class="carousel__item">
        <div class="carousel__content">
          {{ item }}
        </div>
      </div>
    </Slide>

    <template #addons>
      <Navigation />
      <Pagination />
    </template>
  </Carousel>
</template>
```

And use it like the following:

```vue
<template>
  <UCarousel :items="[1, 2, 3]" />
</template>
```

**Comment by Anjali-Git-Hub** [comment]
<template>
  <div class="carousel">
    <div class="carousel-inner">
      <slot name="carousel-item" v-for="(item, index) in items" :item="item" :key="index"></slot>
    </div>
    <button @click="prevSlide">Previous</button>
    <button @click="nextSlide">Next</button>
  </div>
</template>

<script>
export default {
  props: {
    items: Array, // Array of objects
  },
  methods: {
    prevSlide() {
      // Implement logic to show the previous slide
    },
    nextSlide() {
      // Implement logic to show the next slide
    },
  },
};
</script>

<style scoped>
.carousel {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.carousel-inner {
  display: flex;
  overflow: hidden;
}

button {
  margin: 10px;
}
</style>

**Comment by Anjali-Git-Hub** [comment]
`<template>
  <div class="carousel">
    <div class="carousel-inner">
      <slot name="carousel-item" v-for="(item, index) in items" :item="item" :key="index"></slot>
    </div>
    <button @click="prevSlide">Previous</button>
    <button @click="nextSlide">Next</button>
  </div>
</template>

<script>
export default {
  props: {
    items: Array, // Array of objects
  },
  methods: {
    prevSlide() {
      // Implement logic to show the previous slide
    },
    nextSlide() {
      // Implement logic to show the next slide
    },
  },
};
</script>

<style scoped>
.carousel {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.carousel-inner {
  display: flex;
  overflow: hidden;
}

button {
  margin: 10px;
}
</style>
`

**Comment by Anjali-Git-Hub** [comment]
`<template>
  <div class="carousel">
    <div class="carousel-inner">
      <slot name="carousel-item" v-for="(item, index) in items" :item="item" :key="index"></slot>
    </div>
    <button @click="prevSlide">Previous</button>
    <button @click="nextSlide">Next</button>
  </div>
</template>

<script>
export default {
  props: {
    items: Array, // Array of objects
  },
  methods: {
    prevSlide() {
      // Implement logic to show the previous slide
    },
    nextSlide() {
      // Implement logic to show the next slide
    },
  },
};
</script>

<style scoped>
.carousel {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.carousel-inner {
  display: flex;
  overflow: hidden;
}

button {
  margin: 10px;
}
</style>

`
