### ISSUE TITLE
carousel/slide width not updating on page change

### ISSUE THREAD

**Issue by nico-herrera** [ismail9k/vue3-carousel#315]
**Describe the bug**
When changing pages the slide is pushed over about 1/3 of a slide and does not readjust when running carouselRef.updateSlideWidth() or restartCarousel()

**Expected behavior**
Carousel width to update on page visit

**Screenshots**
Current problem:
![Screenshot 2023-06-06 at 9 30 34 AM](https://github.com/ismail9k/vue3-carousel/assets/69056458/09a506d6-b69c-453c-a111-3766a12e7a58)

How it should look:
![Screenshot 2023-06-06 at 9 31 07 AM](https://github.com/ismail9k/vue3-carousel/assets/69056458/2feebc2b-3c2d-41ec-971f-69b15a47a711)

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [chrome]
- Version [113]

**Additional context**
I have looked through the other issues but none work for me, i am on Nuxt ^3.3.3 and using vue3-carousel ^0.3.1

**Comment by ismail9k** [comment]
Hey Nico, in order to help you more could you share with me a working example that regenerates the issue?

**Comment by nico-herrera** [comment]
Just wanted to share some new information, the nested carousel is actually not working because the parent carousel is not adjusting to the correct width of the viewport. I am running both updateSlideWith and restartCarousel methods on @init and it is still not working.

**Comment by nico-herrera** [comment]
Hey @ismail9k , thanks for taking the time to look into this! I agree there's a lot going on, it's not my own codebase so tracking down all the styling has been difficult. Ive found a temporary fix by reassigning the slide with to 33% of the window for the carousel of 3 and using a different option for anything else. I appreciate your response and help!
