### ISSUE TITLE
Throttle config is not applied because handleDragging is defined before prop initialization.

### ISSUE THREAD

**Issue by Eclmist** [ismail9k/vue3-carousel#327]
**Describe the bug**
The `throttle` prop is exposed but does not take effect.
This is because [handleDragging](https://github.com/ismail9k/vue3-carousel/blob/11a2105b42f107cdfd0880c355ea49892c5c4160/src/components/Carousel.ts#L204C19-L204C19) is defined before props have been initialized.

**To Reproduce**
Bind any value to `throttle`, and notice that it does not take effect.

For example:

```
<carousel 
  ...
  :throttle=0>
  ...
</carousel>
```

**Expected behavior**
Mouse/touch drag on carousel should no longer be throttled.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
All versions

**Smartphone (please complete the following information):**
All versions

**Comment by ismail9k** [comment]
The carousel now uses RequestAnimationFrame to throttle the dragging, as seen here: https://github.com/ismail9k/vue3-carousel/pull/422. This improves performance. The throttle property wasn't documented since I was planning to deprecate it anyway.
