### ISSUE TITLE
does not calculate padding automatically at first loading

### ISSUE THREAD

**Issue by Chen-Michael** [ismail9k/vue3-carousel#333]
**Describe the bug**
does not calculate padding automatically at first loading

**To Reproduce**
```javascript
<Carousel :items-to-show="1" :wrap-around="true" snapAlign="start">
      <Slide v-for="(row, key) in bannerList" :key="key">
        <q-img :src="row.image" />
      </Slide>
      <template #addons>
        <Pagination />
      </template>
</Carousel>
```

**Expected behavior**
no extra padding

**Screenshots**
first loading has padding
![截圖 2023-08-30 上午11 20 32](https://github.com/ismail9k/vue3-carousel/assets/11660998/76eaabfd-dc86-46cc-8492-3a6be884b68e)

padding disappear after sliding

![截圖 2023-08-30 上午11 20 44](https://github.com/ismail9k/vue3-carousel/assets/11660998/96367aaa-7b98-4640-91f5-1a512782ebfa)

the banner size is 1640 × 664

![banner-7](https://github.com/ismail9k/vue3-carousel/assets/11660998/ec403588-ed52-4d6e-8a8c-23ac3dd2c122)
![banner-8](https://github.com/ismail9k/vue3-carousel/assets/11660998/a9f33017-c635-4cdc-a5ad-d50c0a2cc6a9)
![banner-9](https://github.com/ismail9k/vue3-carousel/assets/11660998/3b3f036e-3c93-4786-8691-26a4e89493d9)

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser chrome
- Version 115.0.5790.170

**Comment by ismail9k** [comment]
You can add space between slides using `gap` config which is introduced in v0.6.0. Check [here](https://vue3-carousel.ismail9k.com/config.html#available-props)
