### ISSUE TITLE
 How to disable the ability to change the slide when clicking on the pagination

### ISSUE THREAD

**Issue by n4an** [ismail9k/vue3-carousel#334]
How to disable the ability to change the slide when clicking on the pagination?

**Comment by ElenaPrygun** [comment]
<style>
.carousel__pagination-button {
    pointer-events: none;   
}
</style>

**Comment by ismail9k** [comment]
Now you can config the pagination component to `disableOnClick`

Check: https://vue3-carousel.ismail9k.com/addons.html#config
