### ISSUE TITLE
 vue3-carousel not working inside modal

### ISSUE THREAD

**Issue by YouSour** [ismail9k/vue3-carousel#338]
hi, I'm trying to implement  vue3-carousel inside modal, it doesn't work until i inspect element or resize page it works. what 's problem ? thank in advance

**Comment by tjventurini** [comment]
I'm trying to do the same thing. Did you find a solution to this?

**Comment by Kenvdb** [comment]
I'm also trying to achieve the same. It works inside the modal, but the mounting of the carousel takes some time, a few seconds, and causes the view to jump.

Any fixes on this?

**Comment by Kenvdb** [comment]
> I'm also trying to achieve the same. It works inside the modal, but the mounting of the carousel takes some time, a few seconds, and causes the view to jump.
> 
> Any fixes on this?

I've did some digging into the code, and I have a feeling this is causing the problem:
`
setTimeout(() => updateSlideWidth(), 1000)
`
_Line 146 of src/components/Carousel.ts_

**Comment by Tofandel** [comment]
The problem comes from the modal which has either an animation or transition and basically when the modal is mounted with the slider, the computed width is 0

Maybe we could listen for "transitionend" and "animationend" instead of setTimeout
