### ISSUE TITLE
vue3-carousel.js:328 Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'itemsToShow'

### ISSUE THREAD

**Issue by mars1988** [ismail9k/vue3-carousel#339]
all set up working ok but just breakpoints display 'Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'itemsToShow''.  Anyone got the same issue ? 
Vue3/Nuxt3

**Comment by ismail9k** [comment]
Is this issue still happening on the latest version?
