### ISSUE TITLE
Slide should have the ability to differentiate between click and drag event

### ISSUE THREAD

**Issue by AndreiBil** [ismail9k/vue3-carousel#343]
Hello,

Issue:
At this moment if inside the slide I have the image wrapped inside an <a> tag, I cant seem to drag the image so that I can go to the next slide, it acts like a click event instead and redirects me to wherever the <a href=""> points.

Request:
I would like so that when I grab the image and drag it, to be considered a drag instead of a click event so that I can go to the next slide.  And only if I click it, to act like a click event and redirect me the whatever the href value is.

**Comment by DreaMinder** [comment]
That's a frustrating issue... I had something similar in Hooper, but at least I've been able to fix it by firing `e.preventDefault` when `isSliding` is true, but vue3-carousel overrides my vue-events and still clicks on a link somewhere in `handleDragEnd`.

I kinda fixed it by adding `pointer-events: none;` to `.is-dragging` class, I hope there will be no side effects...

**Comment by MKsenni** [comment]
i have some problem ((

**Comment by CommanderStorm** [comment]
@AndreiBil 
This issue was resolved in https://github.com/ismail9k/vue3-carousel/pull/396 ^^
=> can be closed
