### ISSUE TITLE
UI component inside the slide does not change when using the callback function

### ISSUE THREAD

**Issue by Admirated** [ismail9k/vue3-carousel#350]
**Describe the bug**
I'm using the "vue3-carousel" slider: "^0.2.9",
This is what my slider structure looks like, inside the Slide is a UICard component
![image](https://github.com/ismail9k/vue3-carousel/assets/70275437/32af554d-fcc3-4584-995b-f417bc777099)
The UICard component has logic for updating data. I subscribe to an event in a class and pass a callback with this (UICard) context to it; 
![image](https://github.com/ismail9k/vue3-carousel/assets/70275437/3a923de3-efc9-4a8f-8ee1-cecce8609293)
When callBack is called, the following happens:
The required model in the UICard component is changed, (Accordingly, Watch is called on this model, which works correctly and shows that the data is actually updated).
But in the card inside the slider visually nothing changes, the data remains old, and in vue devTools shows that the model is NULL.
In the mobile version I use the same UICard component, which is not inside the slider, and everything works fine there
What are your thoughts on how to solve this problem?

**To Reproduce**
Try changing the component data using the callback function, inside the slider

**Expected behavior**
I expect that the card in which the model has been changed will draw the new data, as in the mobile version without using the slider.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Google Chrome
- Version  119.0.6045.160

**Comment by Tofandel** [comment]
Might be related to #433, issue being that slides are just taken from vNodes and cannot update properly, I have a PR on the way
