### ISSUE TITLE
How change the color of Pagination indicator in Tailwind

### ISSUE THREAD

**Issue by AlexisThink** [ismail9k/vue3-carousel#358]
**Bug**
Trying to change the color of the Paginator has been achieved only locally, since when deploying the changes do not take effect

Deploy on Netlify

**To Reproduce**
In **main.css**

```
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
    --vc-clr-secondary: #bfbfbf !important;
    --vc-clr-primary: #ffffff !important;
}
```
I make the changes to these variables since by reviewing the package code I identified these are the variables that use the Paginator color

**Expected behavior**
This is what the deployment should look like
![localhost_5173_(iPhone 12 Pro)](https://github.com/ismail9k/vue3-carousel/assets/33004685/16fa5009-393a-4828-9bc0-9964aaf14019)
When the display is done the Paginator uses the default colors

**Comment by timlaaan** [comment]
do you found a alernative slider where custom styles is not retardly not possible ?
