### ISSUE TITLE
Ref is not updating on template in carousel component 

### ISSUE THREAD

**Issue by slobodadev** [ismail9k/vue3-carousel#36]
Data is not updating on tempate when you add/remove instance

```
<carousel v-if="presentedImages.length" :items-to-show="2" :snapAlign="'start'" :breakpoints="breakpoints" :wrap-around="true">
    <slide class="slide" v-for="image in presentedImages" :key="image.id">
        <img v-if="image.attachment_url" class="videoFile" :src="image.attachment_url" />
        <div  @click="deleteImage(image.id)" class="fa-stack remove-button cross-btn">
          <i class="fa fa-times"></i>
        </div>
    </slide>
    <template #addons>
        <navigation />
    </template>
</carousel>
```

```
const { images: presentedImages } = toRefs(props);
const deleteImage = (id) => {
    removeAttachment(id).then(res => {
      presentedImages.value = presentedImages.value.filter(img => {
        return img.id !== id;
      });
    })
    .catch(err => console.log(err))
  }
      
```
 FYI: Ref is updating in script.

_Originally posted by @slobodadev in https://github.com/ismail9k/vue3-carousel/discussions/33_

**Comment by ismail9k** [comment]
This is a [sandbox example](https://codesandbox.io/s/vue3-carousel-example-01-02j7p?file=/src/components/Carousel.vue) on how to dynamically remove items from the carousel component.

**Comment by slobodadev** [comment]
> This is a [sandbox example](https://codesandbox.io/s/vue3-carousel-example-01-02j7p?file=/src/components/Carousel.vue) on how to dynamically remove items from the carousel component.

Thank you a lot for your example !
