### ISSUE TITLE
Create a release for package managers

### ISSUE THREAD

**Issue by DrColossos** [ismail9k/vue3-carousel#364]
It would be nice to have a release that can be used by npm, yarn,... there is a version 0.3.2 available, but [NPM](https://www.npmjs.com/package/vue3-carousel) and alike only show 0.3.1.

Looks like the [tag has not been created](https://github.com/ismail9k/vue3-carousel/releases/tag/v0.3.2) (404 error)

**Comment by Cedric-ruiu** [comment]
Hi, same request ;)
