### ISSUE TITLE
Gallery Mode with wrap-around = false doesn't work properly.

### ISSUE THREAD

**Issue by DaleMckeown** [ismail9k/vue3-carousel#367]
**Describe the bug**
When using the double carousel mode, show in the docs as the gallery demo (https://ismail9k.github.io/vue3-carousel/examples.html#gallery). The gallery thumbnails do not correctly navigate to the appropriate slide when setting wrap-around to false, if the slide index is outside of the min/max slide settings.

**To Reproduce**
1. Copy the gallery example from the docs.
2. Set wrap-around to false and set items-to-show to 4.
3. To the slide, add a button that sets the v-model value of the slide to the slide index.
4. Click through the slides. At the end of the list, note that the button does not allow you to select the last couple of slides.

**Expected behavior**
When wrap-around is disabled, the gallery thumbnails should still be selectable.

**Comment by DaleMckeown** [comment]
Here is a codepen that demonstrates the issue:

https://codepen.io/dalemac89/pen/XWGVKNK

To see the issue, load the codepen above and from the bottom carousel click slides 7, 10 and 13. Notice how when clicking slide 13 it then changes you back to slide 12.

Weirdly, the problem doesn't present itself if there are fewer than 10 slides.

**Comment by DaleMckeown** [comment]
For anyone coming across this issue in the future, the workaround for this is to use two separate data properties, one for each of the carousels. When clicking the button in the gallery, update both carousel values. The carousel will internally reset the value for the gallery carosuel without updating the main carousel value.

This will introduce another issue as when you change the slide on the main carousel you'll no longer be updating the value for the gallery carousel. I used the slide-start event on the main carousel to then update the value of the gallery carousel.

This workaround resolved my issue, but it would be cleaner if a proper fix could be found.

**Comment by Tofandel** [comment]
The original reproduction you provided is now working, so this issue has been fixed
