### ISSUE TITLE
How to hide the pagination dots?

### ISSUE THREAD

**Issue by westwashin** [ismail9k/vue3-carousel#369]
i've recently working on a product display menu

`<carousel :items-to-show="3" :navigation="false" :pagination="false">
 <slide v-for="slide in 1" :key="slide">
     <div class="pt active" data-imgbigurl="img/mickey1.jpg">
           <img src="img/mickey1.jpg" alt="" />
      </div>
  </slide>`

i already try to make  it false but it doesn work.
anyone have idea?

**Comment by EtiennePASSOT** [comment]
Do you have more information about your code ? 

With the example, I don't have navigation

```
<script>
import { Carousel, Navigation, Slide } from 'vue3-carousel'
import 'vue3-carousel/dist/carousel.css'
</script>

<template>
  <Carousel :items-to-show="1">
    <Slide v-for="slide in 10" :key="slide">
      {{ slide }}
    </Slide>
  
    <template #addons>
      <Navigation />
    </template>
  </Carousel>
</template>
````

**Comment by ismail9k** [comment]
You can simply remove the Navigation addon component and display only the slides.

```vue
<template>
  <Carousel :items-to-show="1">
    <Slide v-for="slide in 10" :key="slide">
      {{ slide }}
    </Slide>
  </Carousel>
</template>
```
