### ISSUE TITLE
Not loading components

### ISSUE THREAD

**Issue by paulvonber** [ismail9k/vue3-carousel#372]
**Describe the bug**
After update to 0.3.3 doesn't load components anymore

**Screenshots**
![image](https://github.com/ismail9k/vue3-carousel/assets/37245111/953cfc6d-55b6-48e4-8ee1-fef67f8a6ebf)

**Comment by RichAyotte** [comment]
package.json contains
```json
  "main": "dist/carousel.js",
  "module": "dist/carousel.es.js",
```

If you're using Nuxt, it prefers the value in main. 

Temp workaround is to specify the full path of the module.
```ts
import { Carousel, Slide, Pagination, Navigation } from 'vue3-carousel/dist/carousel.es.js'
```

**Comment by paulvonber** [comment]
> If you're using Nuxt, it prefers the value in main. 
> 
> 
> 
> Temp workaround is to specify the full path of the module.
> 
> ```ts
> 
> import { Carousel, Slide, Pagination, Navigation } from 'vue3-carousel/dist/carousel.es.js'
> 
> ```
> 
> 
> 
> 

Yeah that's what I did. Thanks anyway!

**Comment by g4yamanaka** [comment]
I'm also encountering the same issue in a Nuxt 3 environment. By specifying the full path of the module, runtime errors are avoided, but I'm unable to fetch the type information, leading to import errors in TypeScript. This might be a basic question, but could anyone provide a solution to this problem?

**Comment by g4yamanaka** [comment]
I'm also encountering the same issue in a Nuxt 3 environment. By specifying the full path of the module, runtime errors are avoided, but I'm unable to fetch the type information, leading to import errors in TypeScript. This might be a basic question, but could anyone provide a solution to this problem?

**Comment by Darkside73** [comment]
There is a problem if use it in Typescript:
```
Could not find a declaration file for module 'vue3-carousel/dist/carousel.es.js'. 'node_modules/vue3-carousel/dist/carousel.es.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue3-carousel` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-carousel/dist/carousel.es.js';`
  ```
