### ISSUE TITLE
SSR | 'vue3-carousel' does not provide an export named 'Carousel'

### ISSUE THREAD

**Issue by dualklip** [ismail9k/vue3-carousel#377]
**Describe the bug**
When the SSR server is active the log returns an error related with the name of the component

```bash
Starting SSR server on port 13714...
Inertia SSR server started.
file:///var/www/html/bootstrap/ssr/assets/MyComponent-BsSQTya-.js:5
import { Carousel, Slide, Navigation } from "vue3-carousel";
         ^^^^^^^^
SyntaxError: The requested module 'vue3-carousel' does not provide an export named 'Carousel'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async j (file:///var/www/html/node_modules/@inertiajs/vue3/dist/index.esm.js:1:5861)
    at async Server.<anonymous> (file:///var/www/html/node_modules/@inertiajs/core/dist/server.esm.js:1:527)

```

**To Reproduce**
Create new Laravel application with InertiaJS

1. `composer create-project laravel/laravel example-app`
2. `composer require laravel/breeze --dev`
3. `php artisan breeze:install --ssr` (select Inertia + Vue option)
4. `npm install vue3-carousel`
5. Implement the carousel as usual
6. run ssr server `php artisan inertia:start-ssr`
7. Browser the application

**Expected behavior**
A clean console log

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: chrome 124.0.6367.210
- Version 0.3.3

**Comment by simonsheehy** [comment]
I got the same error !

**Comment by christohill** [comment]
It's a workaround but it got me up and running for now, mentioned on https://github.com/gaetansenn/vue3-carousel-nuxt/

```javascript
export default defineNuxtConfig({
  // ...
  alias: {
    'vue3-carousel/dist/carousel': 'vue3-carousel/dist/carousel.es.js',
  },
});
```

https://github.com/gaetansenn/vue3-carousel-nuxt/issues/12#issuecomment-2037042315

**Comment by dualklip** [comment]
> It's a workaround but it got me up and running for now, mentioned on https://github.com/gaetansenn/vue3-carousel-nuxt/
> 
> ```js
> export default defineNuxtConfig({
>   // ...
>   alias: {
>     'vue3-carousel/dist/carousel': 'vue3-carousel/dist/carousel.es.js',
>   },
> });
> ```
> 
> [gaetansenn/vue3-carousel-nuxt#12 (comment)](https://github.com/gaetansenn/vue3-carousel-nuxt/issues/12#issuecomment-2037042315)

It's works. Thank you @christohill 

I changed my import from `import { Carousel, Navigation, Slide } from 'vue3-carousel'` to `import { Carousel, Navigation, Slide } from 'vue3-carousel/dist/carousel'`, and then added your contribution to the `cite.config.js`

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import i18n from 'laravel-vue-i18n/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/js/app.js'],
            ssr: 'resources/js/ssr.js',
            refresh: [
                'resources/views/**',
                'resources/js/**',
                'resources/sass/**',
            ],
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        i18n(),
    ],
    resolve: {
        alias: [{
            find: 'vue3-carousel/dist/carousel',
            replacement : 'node_modules/vue3-carousel/dist/carousel.es.js'
        }]
    },
});

```
