### ISSUE TITLE
Is it possible to disable/destroy carousel on desktop or mobile

### ISSUE THREAD

**Issue by antonyd89** [ismail9k/vue3-carousel#381]
**Is it possible to destroy or do not init the Vue3 Carousel at the some screen resolution? For eg. after 1024 px do not init the Carousel creating?**
I have a case when the Carousel is used only for mobile devices and not for Desktops.

**The feature i would like to have is**
It would be great to have in Vue3Carousel some kind of event/method or property with help of that it would be possible to destroy the carousel.

**Comment by paiva-thiago** [comment]
I also  think that making it responsive or simply disabling on mobile would be a great feature!

**Comment by l-besenyei** [comment]
I would like to have it the other way.
On wider screens where all the slides can fit, disable the carousel, but on smaller size enable it.

I'm thinking of a similar approach to vue-agile where there is an option to disable the carousel
@see https://github.com/lukaszflorczak/vue-agile?tab=readme-ov-file#usage

**Comment by ismail9k** [comment]
@l-besenyei For sure! I’m planning to make it a configurable value that can be turned on and off, providing more flexibility for different use cases.
