### ISSUE TITLE
一个页面两个carousel只能一个正常工作另外一个不工作

### ISSUE THREAD

**Issue by xmzone** [ismail9k/vue3-carousel#384]
一个页面两个carousel只能一个正常工作另外一个不工作

**Comment by xmzone** [comment]
一个页面两个carousel只能一个正常工作另外一个不工作，帮忙看看

**Comment by sepehrisa** [comment]
correct

**Comment by ismail9k** [comment]
I am closing this ticket as it lacks sufficient information to reproduce the issue. If you still need assistance, please create a new ticket or use the discussions tab. Please use English in your communication.
