### ISSUE TITLE
Documentation seemingly incorrect for initDefaultConfig

### ISSUE THREAD

**Issue by alexander-abg** [ismail9k/vue3-carousel#437]
**Describe the bug**

The documentation says the `restartCarousel()` method calls `initDefaultConfig()`, but when I view the source code, it does not.

**To Reproduce**

https://vue3-carousel.ismail9k.com/api/methods.html
https://github.com/ismail9k/vue3-carousel/blob/49d0f5e103b4a629d72ce151937ce4454be6f148/src/components/Carousel/Carousel.ts#L576-L581

**Comment by ismail9k** [comment]
The carousel had a big update:
- https://github.com/ismail9k/vue3-carousel/pull/435
- https://github.com/ismail9k/vue3-carousel/pull/434

Which results in some changes in the internals of the package. This update is not released yet, the documentation will be updated after releasing the latest version
