### ISSUE TITLE
Cutted slides after swipe

### ISSUE THREAD

**Issue by michu9816** [ismail9k/vue3-carousel#438]
**Describe the bug**
Slide does not advance properly - cuts slide by half or about 20%.
As i can see problem starts since version "6.0.0".

**To Reproduce**

1. Go to https://vue3-carousel.ismail9k.com/examples.html
2. Press on slide "1" and swipe it slightly to the left
3. Slide doesn't change to next/previous correctly

**Expected behavior**
Change slide to next in full width

**Screenshots**
![image](https://github.com/user-attachments/assets/d60755e0-1972-422e-9319-67307297ff58)
![image](https://github.com/user-attachments/assets/9d73e112-d137-4996-9a6d-755e347c1d8f)

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 131.0.6778.86

**Additional context**
For me almost always it happens after first try. If your slider works fine,try to swipe to next about 3 times. After bug presents "navigator" also not navigating to full screen slides.

**Comment by ismail9k** [comment]
We are aware of this issue, it would be fixed in the next release
