### ISSUE TITLE
wrapAround not working in breakpoints

### ISSUE THREAD

**Issue by EileenMcCall** [ismail9k/vue3-carousel#44]
When I have :wrapAround="true" set on the carousel element, wrapAround works fine. However, I want to only have pagination (and therefore wrapAround) on smaller page sizes. If you have wrapAround on the carousel element, the slides appear out of order on large screen sizes. However, if you supply wrapAround: true in the breakpoints object, it breaks entirely.

Codepen here: https://codepen.io/eileengmccall/pen/PopozBp

You'll notice that if you shrink down the screen so the breakpoint activates, the number on the slide jumps to 5 and stays there as soon as you try to paginate.

Any help would be appreciated!

**Comment by michalpaukert** [comment]
Could you check this with new version?
I think this could be fixed with my last commit.
