### ISSUE TITLE
Configurable Cloned Items for Wrap-Around

### ISSUE THREAD

**Issue by ismail9k** [ismail9k/vue3-carousel#445]
## Description
Add a new configuration option, `clonedItemsCount`, to control the number of items cloned when the `wrapAround` feature is enabled. This will provide developers greater flexibility and customization options for wrap-around behavior.

### New Config Option
- **Name**: `clonedItemsCount`
- **Default**: `itemsToShow + 1`

### Behavior
- When `clonedItemsCount` exceeds the total number of slides (`slides.length`), the remaining clones should be represented by empty slide elements. This ensures proper behavior without breaking the layout.
- Empty slides should be styled consistently to avoid visual inconsistencies.

### Implementation Details
- **Default Logic**:
  - Clone `Math.min(clonedItemsCount, slides.length)` slides.
  - If `clonedItemsCount > slides.length`, generate `clonedItemsCount - slides.length` empty slides.

### Example Usage
```vue
<Carousel 
  :itemsToShow="3" 
  :wrapAround="true" 
  :clonedItemsCount="5"
>
  <!-- Slides here -->
</Carousel>
```

In this example, if slides.length === 3, it will generate 3 clones plus 2 empty slides.

**Comment by Tofandel** [comment]
> When clonedItemsCount exceeds the total number of slides (slides.length), the remaining clones should be represented by empty slide elements. This ensures proper behavior without breaking the layout.
> 
Empty slides should be styled consistently to avoid visual inconsistencies.

It should duplicate the existing slides to be a proper wraparound, there should be no visible gap (which is what was done in #444)

**Comment by ismail9k** [comment]
Thank you for sharing this idea, I like the concept a lot, but implementing it would introduce some complexity. Here are a couple of challenges we’d need to address:
	1.	Currently, the active slide doesn’t update in real-time during dragging—it only updates after the dragging ends. To support this behavior, we’d need to modify the logic to continuously track the active slide while the user is dragging.
	2.	Adding or removing cloned slides dynamically would require careful management of the cloneOffset. This ensures the carousel’s position remains accurate and doesn’t shift unexpectedly when slides are added or removed mid-drag.

 I’ll explore this idea further to see if it’s possible to implement without overengineering the solution. It’s an interesting edge case to cover, and finding the right balance between performance and complexity is always worth pursuing!
