### ISSUE TITLE
Slide size not refreshing

### ISSUE THREAD

**Issue by michu9816** [ismail9k/vue3-carousel#451]
**Describe the bug**
When the page loads, the slide size is incorrect. Hot reload page fixes that issue. All versions before 0.5.0 works fine.

**To Reproduce**
Can't reproduce it on stackblitz. I can see problem only on my project.

1. Move first slide to right
2. Slide moves for 0.15px
3. Change one line in project (remove console log) and save to hot update page
4. Slides works good

**Expected behavior**
Slide moves for correct pixels number

**Screenshots**
1. Screenshot default
![image](https://github.com/user-attachments/assets/2f8e528f-f578-4461-949a-b7ecd3b1cc93)

2. After swipe to right - you can see that div  is cropped - transform: translateX(-5.12484px); (slide doesn't change, still it's 1 of 2)
![image](https://github.com/user-attachments/assets/ff5c1fd9-2511-4d3c-bfbb-0a0d50eeef6b)

3. Slide size
![image](https://github.com/user-attachments/assets/7ef4c351-c8ae-4456-af11-b28062abd8e1)

4. Slide size after hot update
![image](https://github.com/user-attachments/assets/5c587f4e-d306-4d05-b00d-7b15a4380016)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 131.0.6778.109

**Additional context**
My project loads data asynchroniously. I'm not sure if it can helps. I tried to load some data after timeout on stackblitz but it also looked correct, maybe someone will have some idea.

My config
```
 const carouselConfig = computed(() => {
      return {
        itemsToShow: props.devicesPerPage,
        gap: 5,
        snapAlign: 'start',
        enabled: parseInt(devicesCarousel.value?.data?.slidesCount) > parseInt(props.devicesPerPage), // prevent move if only one slide available
        i18n: {
          ariaNavigateToSlide: 'Strona {slideNumber}',
        },
      };
    });
```

**Comment by Tofandel** [comment]
Do you have an infinite animation somewhere on the page by any chance?

I was fixing something similar with #441

**Comment by michu9816** [comment]
In console i get 
```
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 50, pseudoElement: '', type: 'animationstart', …}
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 30, pseudoElement: '', type: 'animationstart', …}
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 17, pseudoElement: '', type: 'animationstart', …}
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 42, pseudoElement: '', type: 'animationstart', …}
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 8, pseudoElement: '', type: 'animationstart', …}
AnimationEvent {isTrusted: true, animationName: 'moveRight-335700b7', elapsedTime: 0, pseudoElement: '', type: 'animationstart', …}
```
When i change ignoreAnimations to true nothing changes.
I'll try to rewrite carousel again and check case when my div causes this problem.

**Comment by Tofandel** [comment]
> When i change ignoreAnimations to true nothing changes.
The PR is not yet merged 

In your package.json you can use `"vue3-carousel": "npm:@tofandel/vue3-carousel",` to try it out

**Comment by Tofandel** [comment]
So what's going on:

You have an animation with a transform that is completely unrelated to the carousel, it's not an animation to a parent element
But it's still added to the list of transform elements

I added a check in #441 so that if the animation is on an element that is not a parent of the carousel, it is ignored

**Comment by michu9816** [comment]
> The PR is not yet merged
Ohh sory, i've missed that information. 

https://stackblitz.com/edit/vue3-carousel-example-basic-zmcprmzv?file=src%2FApp.vue
You can see my animation here. During that animation slider doesn't work properly, when it's finished everything is ok.

I'm not sure but even if i change my branch to yours my carousel still not working good. And i have no idea why it's ok after hot update (save files) ...

**Comment by Tofandel** [comment]
Yes I could reproduce and I just fixed the issue, overrides don't seem to work on stackblitz
https://stackblitz.com/edit/vue3-carousel-example-basic-e1nkyuis?file=src%2FApp.vue,package.json

**Comment by michu9816** [comment]
Thanks, works good now :)
