### ISSUE TITLE
Incorrect Vue peer dependency

### ISSUE THREAD

**Issue by BR0kEN-** [ismail9k/vue3-carousel#459]
vue3-carousel 0.9.0 started to use Vue's [useId()](https://vuejs.org/api/composition-api-helpers#useId) that has been added in Vue 3.5 (see https://vuejs.org/api/composition-api-helpers#useId).

Though, the peer dependency still says vue3-carousel is compatible with Vue 3.2.

https://github.com/ismail9k/vue3-carousel/blob/6a254cc51ef59d256679353ed2e8a05932730e56/package.json#L91-L93

> [!TIP]
> It would be great if breaking changes like this and https://github.com/ismail9k/vue3-carousel/issues/457 were introduced in a new major version so automatic minor/patch updates don't come with this kind of surprises.

**Comment by ismail9k** [comment]
Thank you for the feedback! You’re correct `useId()` requires Vue 3.5, and the peer dependency range should reflect that. We’ll update it to avoid confusion. As the library is still under active development, we’re working towards a stable v1.0.0 release soon, where such breaking changes will follow semantic versioning more strictly. We appreciate your patience and understanding

**Comment by BR0kEN-** [comment]
Sure, np.

Is it possible to release 1.0 with 3.2 support?

**Comment by ismail9k** [comment]
Thanks for your understanding! We’d like to benefit from the features and optimizations in Vue 3.5, which makes supporting Vue 3.2 challenging. That said, I’ll reevaluate the feasibility of adding Vue 3.2 support for the 1.0 release, but I can’t make any promises at this stage.
