### ISSUE TITLE
Can't click inside of a slide

### ISSUE THREAD

**Issue by cs1m0n** [ismail9k/vue3-carousel#46]
**Describe the bug**
If you have a button to click on into a slide, the mobile will treat the click as a drag and it does nothing when you click on it.

**To Reproduce**
1. Add a <button> tag inside of a carousel slide
2. Click on it on mobile (Chrome's inspect element with toggle device toolbar on works also)
3. Nothing happens

**Expected behavior**
The click event is treated differently than the drag event and the button does what was meant to do.

**Comment by jonasdulay28** [comment]
up for this. the plugin is good. If this will be fixed soon it will be more awesome

**Comment by jonasdulay28** [comment]
`<slide v-for="(announcement, index) in announcements" :key="index">
              <img
                :src="announcement.image_path"
                :alt="announcement.title"
                @click="directToPath(announcement.redirect_url)"
                @touchend="directToPath(announcement.redirect_url)"
                class="img-fluid"
              />
            </slide>`

What i did is just put a carousel for my announcements that contains images however i tried to click the image and the @click is not firing, so i tried @touchend and it works. This is only my temporary fix. i hope that you can fix this issue. Thank you
