### ISSUE TITLE
Custom Navigation style & custom slide item more than one

### ISSUE THREAD

**Issue by atommanz** [ismail9k/vue3-carousel#51]
Custom Navigation style & custom slide item more than one

**Comment by atommanz** [comment]
.carousel__prev, .carousel__next
this css that i need to custom

**Comment by ismail9k** [comment]
For style customization check here: #17, #28, #56
`itemsToScroll` prop is added in `0.1.20`, please check: https://ismail9k.github.io/vue3-carousel/getting-started.html#available-props

**Comment by atommanz** [comment]
@ismail9k Thank you bro !
