### ISSUE TITLE
Customizing style

### ISSUE THREAD

**Issue by alyaizzaty** [ismail9k/vue3-carousel#56]
Hi. I'm new in using component plugin like these.  I'm  trying to applied your component in my project and it working. But I'm wondering if I can customizing the style of pagination button. If it possible, can you guide me how?

**Comment by ismail9k** [comment]
You can easily customize the pagination styles, by overwriting the pagination styling classes: `carousel__pagination`, `carousel__pagination-item`, `carousel__pagination-button`, and `carousel__pagination-button--active`.
Check the here [default pagination styles](https://github.com/ismail9k/vue3-carousel/blob/master/src/styles/pagination.css) that shipped with the carousel.

**Comment by apoorvatyagi61** [comment]
I want to change the rectangle shapes of pagination to circle but couldn't find any way. Found this only related ticket to pagination. Could you please help? @ismail9k

**Comment by ismail9k** [comment]
@apoorvatyagi61 You have two options to do so, First you can overwrite the CSS variables like the following:
```
<style>
:root {
  --vc-pgn-width: 12px;
  --vc-pgn-height: 12px;
  --vc-pgn-border-radius: 6px;
}
</style>
```

Or you can easily overwrite the pagination style classes:


```
<style>
.carousel__pagination-button::after {
  width: 12px;
  height: 12px;
  border-radius: 6px;
}
</style>
```

**Comment by DyDev-1** [comment]
:deep(.carousel__pagination-button::after) {
  width: 12px;
  height: 12px;
  border-radius: 50%;
}
