### ISSUE TITLE
Page-Scrolling is prevented on mobile devices 

### ISSUE THREAD

**Issue by mitras2** [ismail9k/vue3-carousel#61]
**Description**
I mobile devices I can not scroll any further when I reach the carousel. Probably the .preventDefault breaks the normal page scrolling if the user starts the touch on the carousel.

**To Reproduce**
1. Go to [dev.agapegemeinde.de](https://dev.agapegemeinde.de/) with a mobile device (iOS+Safari and Android+Firefox tested)
2. Scroll down the page until you reach "Gruppen und Aktionen" try to scroll further down (the carousel will always prevent it)

**Expected behavior**
A threshold of movement to the side before the scroll down is prevented

**Tested on (Smartphone)**
 - Device: iPhone SE (Safari), Samsung Galaxy S7 (Firefox v.88.1.4)

**Comment by ismail9k** [comment]
`PreventDefault` is disabled for touching devices [check](https://github.com/ismail9k/vue3-carousel/blob/master/src/components/Carousel.ts#L213) in `v0.1.20`. Please update the carousel to the latest version.
