### ISSUE TITLE
Support for Nuxt JS Composition API

### ISSUE THREAD

**Issue by vphilot** [ismail9k/vue3-carousel#64]
**Is your feature request related to a problem? Please describe.**
Problem: When trying to install vue-carousel in a Nuxt project, it can't resolve the dependency tree since Nuxt still is based on Vue2: 

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: vue@2.6.12
npm ERR! node_modules/vue
``` 

**Describe the solution you'd like**
Nuxt doesn't support Vue3 yet, but it does provide a Composition API package via `@nuxtjs/composition-api`. Is there any way we can make it work? Thank you.

**Comment by ismail9k** [comment]
This package doesn't support Vue2 yet #13
