### ISSUE TITLE
wrapAround not working properly

### ISSUE THREAD

**Issue by Capaldi96** [ismail9k/vue3-carousel#7]
WrapAround not working properly when using 2 carousels on the same page, One always resets when clicking on next/previous.

**Comment by Capaldi96** [comment]
Do i pass a counter property in options to use multiple carousels?

**Comment by ismail9k** [comment]
No, the carousel should figure it out, just make sure to use the latest version.

**Comment by Capaldi96** [comment]
Thanks! Great work.
