### ISSUE TITLE
Not working with dynamic componnet as a slide

### ISSUE THREAD

**Issue by Exlord** [ismail9k/vue3-carousel#73]
**Describe the bug**
When another component is used inside slide it is not compiled and is treated like a unknown tag

**To Reproduce**
https://codesandbox.io/s/practical-morning-96bng?file=/src/components/MyCarousel.vue

**Expected behavior**
Requested Component is rendered inside the slide

**Comment by sebsasto** [comment]
@Exlord it was an error about how you were importing your component.

You should do:
`import MyComp from "./MyComp.vue";` instead of `import { MyComp } from "./MyComp.vue";`
