### ISSUE TITLE
Hello, what's the timeline for the roadmap? I am keenly waiting on the very next checkbox -> being able to style the active/inactive slides to create a coverflow effect etc. I ❤️  the stability/minimalism on this component!

### ISSUE THREAD

**Issue by ismail9k** [ismail9k/vue3-carousel#76]
Hello, what's the timeline for the roadmap? I am keenly waiting on the very next checkbox -> being able to style the active/inactive slides to create a coverflow effect etc. I ❤️  the stability/minimalism on this component!

_Originally posted by @oneWaveAdrian in https://github.com/ismail9k/vue3-carousel/discussions/32#discussioncomment-940702_

**Comment by oneWaveAdrian** [comment]
@ismail9k any update on this timeline?

**Comment by ismail9k** [comment]
Added in `v0.1.24`, and [docs](https://ismail9k.github.io/vue3-carousel/examples.html#active-classes) is updated. 🎉🎉
