### ISSUE TITLE
Getting Error In console [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event ?

### ISSUE THREAD

**Issue by geminigeek** [ismail9k/vue3-carousel#90]
Getting console error/info "[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event Consider marking event handler as 'passive' to make the page more responsive" 

i am planning to use multiple carousel component on a page this might cause performance issue ?

the issue is also in the example page https://ismail9k.github.io/vue3-carousel/examples.html#basic-example
just reload and check the console.log in Chrome

Expected behavior : no violation warning

**Comment by LighthouseKeeperYN** [comment]
Still reproducable.

**Comment by ismail9k** [comment]
This warning is fixed in the latest version

**Comment by jlecointecaplaser** [comment]
This error is still relevant in v0.2.9 as well as on the sample page: https://ismail9k.github.io/vue3-carousel/examples.html#basic-example
