### ISSUE TITLE
How to change arrow's icon?

### ISSUE THREAD

**Issue by MicsLin** [ismail9k/vue3-carousel#93]
Thank you for your sharing,it's very useful for me!

But if I would like to change the arrow icons,how can I do?

I checked "/node_modules/vue3-carousel/**carousel.css**" already,
but there's no way to edit that.

Plz help me,thx.

**Comment by ismail9k** [comment]
Thank you :) 
Please check this issue #17 for more info, and let me know if you have any further issues.
